export {
  BROWSER_CLOSED_MESSAGE,
  BROWSER_DIR,
  BROWSER_PROFILE_DIR,
  BROWSER_USER,
  BrowserError,
  type BrowserEvent,
  type BrowserInfo,
  type BrowserListener,
  BrowserService,
  type BrowserServiceDeps,
  browserPidFile,
  browserSignalSpec,
  CDP_PORT,
  CDP_RELAY_SCRIPT,
  chromiumCommand,
  chromiumExecSpec,
  relayExecSpec,
} from './service.js';
