import assert from 'node:assert/strict';
import http from 'node:http';
import type { AddressInfo } from 'node:net';
import { after, before, describe, it } from 'node:test';

import { type Config, loadConfig } from '../config.js';
import {
  createPrRun,
  createRecurringTask,
  createRepository,
  createSession,
  type Database,
  getSession,
  IN_MEMORY,
  isDeliveryStage,
  openDatabase,
  type PrRunStatus,
  type Session,
  type SessionStatus,
  setSetting,
  type Story,
  syncStories,
  updatePrRun,
  updateSession,
} from '../db/index.js';
import type { ExecOutput, ExecSpec } from '../docker/index.js';
import { GithubApiError, openPullRequest } from '../lib/github.js';
import { UsageLimitHold } from '../limits/index.js';
import type { SessionContainerView } from '../orchestrator/index.js';
import { PrFeedbackError } from '../prfeedback/index.js';
import type {
  PublishedReview,
  ReviewPassResult,
  ReviewPublisher,
  ReviewReport,
  ReviewTarget,
} from '../review/index.js';
import { CONTAINER_REPO_DIR, type SessionContainers, type SessionExecutor } from '../sessions/index.js';
import { COMMIT_COUNT_SCRIPT, type CommitCount, commitCountExecSpec, countBranchCommits } from './commits.js';
import { pullRequestBody, pullRequestNumber, pullRequestTitle } from './pull-request.js';
import { PUSH_SCRIPT, pushExecSpec } from './push.js';
import { type FeedbackSolver, ReviewStep, type SessionReviewer } from './review-step.js';
import { createDeliveryService, DeliveryError, type PullRequestOpener } from './service.js';

const TOKEN = 'ghp_exampleTokenValue1234';

function story(input: Partial<Story> & Pick<Story, 'storyId' | 'priority' | 'status'>): Story {
  return {
    id: 0,
    sessionId: 's',
    title: input.storyId,
    commitSha: null,
    createdAt: '',
    updatedAt: '',
    ...input,
  };
}

describe('the push command', () => {
  it('pushes the branch by name, with an upstream and never a force', () => {
    const spec = pushExecSpec('chief/add-login');
    assert.deepEqual(spec.cmd, ['/bin/sh', '-c', PUSH_SCRIPT]);
    assert.equal(spec.workingDir, CONTAINER_REPO_DIR);
    assert.match(PUSH_SCRIPT, /git push --set-upstream origin "\$CHIEF_FEATURE_BRANCH"/);
    assert.doesNotMatch(PUSH_SCRIPT, /--force|\+refs/);
  });

  it('passes the branch in the environment, never inside the script', () => {
    const spec = pushExecSpec('chief/weird; rm -rf /');
    assert.deepEqual(
      [...(spec.env ?? [])],
      ['CHIEF_FEATURE_BRANCH=chief/weird; rm -rf /', `CHIEF_REPO_DIR=${CONTAINER_REPO_DIR}`],
    );
    assert.doesNotMatch(PUSH_SCRIPT, /rm -rf/);
  });
});

describe('the pull request body', () => {
  const session = {
    id: 'session-1',
    name: 'add-login',
    featureBranch: 'chief/add-login',
    prTargetBranch: 'develop' as const,
  };
  const stories = [
    story({ storyId: 'US-002', priority: 2, status: 'done', title: 'Second', commitSha: 'abcdef1234' }),
    story({ storyId: 'US-001', priority: 1, status: 'done', title: 'First' }),
  ];

  it('is the session name for a title', () => {
    assert.equal(pullRequestTitle({ name: 'add-login' }), 'add-login');
  });

  it('lists the completed stories by id and title, in priority order', () => {
    const body = pullRequestBody({ session, stories, publicUrl: '' });
    assert.match(body, /## Completed stories \(2\/2\)/);
    assert.ok(body.indexOf('**US-001** — First') < body.indexOf('**US-002** — Second'));
    assert.match(body, /\(`abcdef1`\)/);
  });

  it('says it was generated by chief-web, and links back when the URL is known', () => {
    assert.match(
      pullRequestBody({ session, stories, publicUrl: '' }),
      /Generated by chief-web from session `add-login`/,
    );
    assert.match(
      pullRequestBody({ session, stories, publicUrl: 'https://chief.example.com' }),
      /\[session `add-login`\]\(https:\/\/chief\.example\.com\/sessions\/session-1\)/,
    );
  });

  it('names the branches it is between, and any story left outstanding', () => {
    const body = pullRequestBody({
      session,
      stories: [...stories, story({ storyId: 'US-003', priority: 3, status: 'todo', title: 'Third' })],
      publicUrl: '',
    });
    assert.match(body, /`chief\/add-login` → `develop`/);
    assert.match(body, /## Still outstanding \(1\)/);
    assert.match(body, /\*\*US-003\*\* — Third \(todo\)/);
  });
});

/**
 * The GitHub half, against a real HTTP server speaking the REST protocol —
 * the same approach `FakeDockerDaemon` takes, so `fetch`, the headers and the
 * status mapping are all exercised for real.
 */
describe('opening a pull request', () => {
  let baseUrl: string;
  let server: http.Server;
  /** What the stub answers, keyed by `<method> <pathname>`. */
  let replies: Record<string, { status: number; body: unknown }> = {};
  let requests: { method: string; url: string; body: unknown; auth?: string | undefined }[] = [];

  before(async () => {
    server = http.createServer((req, res) => {
      const chunks: Buffer[] = [];
      req.on('data', (chunk: Buffer) => chunks.push(chunk));
      req.on('end', () => {
        const raw = Buffer.concat(chunks).toString('utf8');
        const url = new URL(req.url ?? '/', 'http://localhost');
        requests.push({
          method: req.method ?? '',
          url: req.url ?? '',
          body: raw === '' ? null : (JSON.parse(raw) as unknown),
          auth: req.headers.authorization,
        });
        const reply = replies[`${req.method ?? ''} ${url.pathname}`] ?? {
          status: 404,
          body: { message: 'Not Found' },
        };
        res.writeHead(reply.status, { 'content-type': 'application/json' });
        res.end(JSON.stringify(reply.body));
      });
    });
    server.listen(0, '127.0.0.1');
    await new Promise((resolve) => server.once('listening', resolve));
    baseUrl = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  });

  after(async () => {
    await new Promise((resolve) => server.close(resolve));
  });

  const input = {
    slug: 'acme/demo',
    head: 'chief/add-login',
    base: 'develop',
    title: 'add-login',
    body: 'Generated by chief-web.',
  };

  it('creates one when there is none, with the title, body, head and base', async () => {
    replies = {
      'GET /repos/acme/demo/pulls': { status: 200, body: [] },
      'POST /repos/acme/demo/pulls': {
        status: 201,
        body: {
          number: 7,
          html_url: 'https://github.com/acme/demo/pull/7',
          state: 'open',
          node_id: 'PR_kwDO7',
          draft: true,
        },
      },
    };
    requests = [];

    const opened = await openPullRequest(TOKEN, baseUrl, input);
    assert.deepEqual(opened, {
      pullRequest: {
        number: 7,
        url: 'https://github.com/acme/demo/pull/7',
        state: 'open',
        // Carried through for the undraft, which is GraphQL-only (US-001).
        nodeId: 'PR_kwDO7',
        draft: true,
      },
      adopted: false,
    });

    const [lookup, created] = requests;
    // The head of a same-repository branch is still qualified `owner:branch`.
    assert.match(lookup?.url ?? '', /head=acme%3Achief%2Fadd-login/);
    assert.match(lookup?.url ?? '', /base=develop/);
    assert.equal(created?.auth, `Bearer ${TOKEN}`);
    assert.deepEqual(created?.body, {
      title: 'add-login',
      body: 'Generated by chief-web.',
      head: 'chief/add-login',
      base: 'develop',
      // Every session pull request opens as a draft; delivery marks it ready
      // once the review chain is done.
      draft: true,
    });
  });

  it('adopts the existing one instead of creating a duplicate', async () => {
    replies = {
      'GET /repos/acme/demo/pulls': {
        status: 200,
        body: [
          {
            number: 4,
            html_url: 'https://github.com/acme/demo/pull/4',
            state: 'open',
            node_id: 'PR_kwDO4',
            draft: false,
          },
        ],
      },
    };
    requests = [];

    const opened = await openPullRequest(TOKEN, baseUrl, input);
    assert.equal(opened.adopted, true);
    assert.equal(opened.pullRequest.url, 'https://github.com/acme/demo/pull/4');
    // An adopted pull request answers both undraft questions too: what to act
    // on, and whether there is anything to act on.
    assert.equal(opened.pullRequest.nodeId, 'PR_kwDO4');
    assert.equal(opened.pullRequest.draft, false);
    // Nothing was posted: the lookup is the only call.
    assert.deepEqual(requests.map((request) => request.method), ['GET']);
  });

  it('adopts the one a race created, when GitHub answers 422', async () => {
    let lookups = 0;
    replies = {
      'POST /repos/acme/demo/pulls': {
        status: 422,
        body: {
          message: 'Validation Failed',
          errors: [{ message: 'A pull request already exists for acme:chief/add-login.' }],
        },
      },
    };
    // The first lookup finds nothing, the one after the 422 finds the race's.
    server.removeAllListeners('request');
    server.on('request', (req, res) => {
      req.resume();
      const url = new URL(req.url ?? '/', 'http://localhost');
      if (req.method === 'GET') {
        lookups += 1;
        res.writeHead(200, { 'content-type': 'application/json' });
        res.end(
          JSON.stringify(
            lookups === 1
              ? []
              : [{ number: 9, html_url: 'https://github.com/acme/demo/pull/9', state: 'open' }],
          ),
        );
        return;
      }
      const reply = replies[`POST ${url.pathname}`] ?? { status: 500, body: {} };
      res.writeHead(reply.status, { 'content-type': 'application/json' });
      res.end(JSON.stringify(reply.body));
    });

    const opened = await openPullRequest(TOKEN, baseUrl, input);
    assert.equal(opened.adopted, true);
    assert.equal(opened.pullRequest.number, 9);
    assert.equal(lookups, 2);
  });

  it('reports what GitHub said when it refuses for another reason', async () => {
    server.removeAllListeners('request');
    server.on('request', (req, res) => {
      req.resume();
      if (req.method === 'GET') {
        res.writeHead(200, { 'content-type': 'application/json' });
        res.end('[]');
        return;
      }
      res.writeHead(422, { 'content-type': 'application/json' });
      res.end(
        JSON.stringify({
          message: 'Validation Failed',
          errors: [{ message: 'No commits between develop and chief/add-login' }],
        }),
      );
    });

    const failure = await openPullRequest(TOKEN, baseUrl, input).catch((cause: unknown) => cause);
    assert.ok(failure instanceof GithubApiError);
    assert.equal(failure.code, 'github_rejected');
    assert.match(failure.message, /No commits between develop and chief\/add-login/);
  });
});

/** A session container that answers whatever the test scripts. */
class World {
  readonly config: Config;
  readonly db: Database;
  readonly session: Session;
  readonly containers: SessionContainers;
  readonly execs: ExecSpec[] = [];
  /** What the push exec answers with. */
  push: ExecOutput = { exitCode: 0, stdout: '', stderr: 'Branch set up to track origin.', timedOut: false };
  /** What `git rev-list --count` answers with; two commits by default. */
  commits: ExecOutput = { exitCode: 0, stdout: '2\n', stderr: '', timedOut: false };
  containerFailure: Error | null = null;

  constructor(options: { slug?: string; publicUrl?: string; recurring?: boolean } = {}) {
    this.config = loadConfig(
      options.publicUrl === undefined ? {} : { PUBLIC_URL: options.publicUrl },
    );
    this.db = openDatabase(IN_MEMORY);
    const repository = createRepository(this.db, {
      name: 'demo',
      sshUrl: 'git@github.com:acme/demo.git',
      githubSlug: options.slug ?? 'acme/demo',
    });
    // A run of a recurring task (US-006) is the one session that may finish
    // without a pull request, so it is the one this can create either way.
    const task =
      options.recurring === true
        ? createRecurringTask(this.db, {
            repositoryId: repository.id,
            name: 'nightly-rector',
            prompt: 'Run rector and fix what it reports.',
            cronExpression: '0 3 * * *',
            baseBranch: 'main',
            prTarget: 'develop',
          })
        : null;
    this.session =
      updateSession(
        this.db,
        createSession(this.db, {
          repositoryId: repository.id,
          name: 'add-login',
          baseBranch: 'main',
          prTargetBranch: 'develop',
          recurringTaskId: task?.id ?? null,
        }).id,
        { status: 'building' },
      ) ?? (undefined as never);
    setSetting(this.db, 'github_token', TOKEN);
    syncStories(this.db, this.session.id, [
      { storyId: 'US-001', title: 'First', priority: 1, status: 'done' },
      { storyId: 'US-002', title: 'Second', priority: 2, status: 'done' },
    ]);

    this.containers = {
      start: (): Promise<SessionContainerView> =>
        this.containerFailure === null
          ? Promise.resolve({
              id: 'container-1',
              name: 'chief-web-add-login',
              running: true,
              state: 'running',
            })
          : Promise.reject(this.containerFailure),
      remove: (): Promise<void> => Promise.resolve(),
    };
  }

  get exec(): SessionExecutor {
    return {
      runExec: (_container: string, spec: ExecSpec): Promise<ExecOutput> => {
        this.execs.push(spec);
        return Promise.resolve(spec.cmd[2] === COMMIT_COUNT_SCRIPT ? this.commits : this.push);
      },
    };
  }

  reload(): Session {
    return getSession(this.db, this.session.id) ?? (undefined as never);
  }

  stories(): Story[] {
    return [
      story({ storyId: 'US-001', priority: 1, status: 'done' }),
      story({ storyId: 'US-002', priority: 2, status: 'done' }),
    ];
  }
}

/** A {@link PullRequestOpener} the test scripts. */
class FakeOpener implements PullRequestOpener {
  readonly calls: { token: string; input: Parameters<PullRequestOpener['open']>[1] }[] = [];
  /** Every undraft, in order: what the delivery asked GitHub to mark ready. */
  readonly ready: { token: string; pullRequestId: string }[] = [];
  /** Every lookup a retry did to find the pull request it has to undraft. */
  readonly lookups: { token: string; input: Parameters<PullRequestOpener['find']>[1] }[] = [];
  /** Answers the lookup with this instead of a pull request, when set. */
  findFailure: Error | null = null;
  /** Whether the lookup finds anything: a closed pull request is `false`. */
  open_ = true;
  adopted = false;
  failure: Error | null = null;
  /** Answers the undraft with this instead of succeeding, when set. */
  readyFailure: Error | null = null;
  /** The state the opened/adopted pull request comes back in. */
  draft = true;
  nodeId: string | null = 'PR_kwDO7';
  url = 'https://github.com/acme/demo/pull/7';

  open(
    token: string,
    input: Parameters<PullRequestOpener['open']>[1],
  ): ReturnType<PullRequestOpener['open']> {
    this.calls.push({ token, input });
    if (this.failure !== null) return Promise.reject(this.failure);
    return Promise.resolve({
      pullRequest: {
        number: 7,
        url: this.url,
        state: 'open',
        nodeId: this.nodeId,
        draft: this.draft,
      },
      adopted: this.adopted,
    });
  }

  find(
    token: string,
    input: Parameters<PullRequestOpener['find']>[1],
  ): ReturnType<PullRequestOpener['find']> {
    this.lookups.push({ token, input });
    if (this.findFailure !== null) return Promise.reject(this.findFailure);
    if (!this.open_) return Promise.resolve(null);
    return Promise.resolve({
      number: 7,
      url: this.url,
      state: 'open',
      nodeId: this.nodeId,
      draft: this.draft,
    });
  }

  markReady(
    token: string,
    pullRequestId: string,
  ): ReturnType<PullRequestOpener['markReady']> {
    this.ready.push({ token, pullRequestId });
    if (this.readyFailure !== null) return Promise.reject(this.readyFailure);
    // The real client answers an already-ready pull request the same way it
    // answers one it just undrafted: success.
    return Promise.resolve({ isDraft: false, alreadyReady: !this.draft });
  }
}

describe('delivering a finished session', () => {
  it('pushes, opens the pull request, and leaves the session pr-open', async () => {
    const world = new World({ publicUrl: 'https://chief.example.com/' });
    const opener = new FakeOpener();
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      opener,
    );

    await delivery.complete(world.session, world.stories());

    assert.equal(world.execs.length, 1);
    assert.deepEqual(world.execs[0]?.cmd, ['/bin/sh', '-c', PUSH_SCRIPT]);

    const call = opener.calls[0];
    assert.equal(call?.token, TOKEN);
    assert.equal(call?.input.slug, 'acme/demo');
    assert.equal(call?.input.head, 'chief/add-login');
    assert.equal(call?.input.base, 'develop');
    assert.equal(call?.input.title, 'add-login');
    assert.match(call?.input.body ?? '', /\*\*US-001\*\* — US-001/);
    assert.match(call?.input.body ?? '', /https:\/\/chief\.example\.com\/sessions\//);

    // The pull request is open, so the session is `pr-open` and not `finished`
    // (US-002); only the sync moves it on from there.
    const delivered = world.reload();
    assert.equal(delivered.status, 'pr-open');
    assert.equal(delivered.prUrl, 'https://github.com/acme/demo/pull/7');
    assert.equal(delivered.lastError, null);
  });

  it('undrafts the pull request it opened when no review will run', async () => {
    const world = new World();
    const opener = new FakeOpener();
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      opener,
    );

    await delivery.complete(world.session, world.stories());

    // The pull request is opened as a draft and released straight away, so a
    // session without code review ends exactly where it always did (US-003).
    assert.deepEqual(opener.ready, [{ token: TOKEN, pullRequestId: 'PR_kwDO7' }]);
    const delivered = world.reload();
    assert.equal(delivered.status, 'pr-open');
    assert.equal(delivered.prUrl, 'https://github.com/acme/demo/pull/7');
  });

  it('undrafts an adopted pull request that is already ready', async () => {
    const world = new World();
    const opener = new FakeOpener();
    opener.adopted = true;
    opener.draft = false;
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      opener,
    );

    await delivery.complete(world.session, world.stories());

    // The undraft is idempotent, so it is called without reading the flag
    // first — and the refusal it gets back is not an error.
    assert.equal(opener.ready.length, 1);
    assert.equal(world.reload().status, 'pr-open');
    assert.equal(world.reload().lastError, null);
  });

  it('leaves a ready pull request alone when GitHub sent no node id', async () => {
    const world = new World();
    const opener = new FakeOpener();
    opener.adopted = true;
    opener.draft = false;
    opener.nodeId = null;
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      opener,
    );

    await delivery.complete(world.session, world.stories());

    assert.equal(opener.ready.length, 0, 'there is nothing to call the mutation with');
    assert.equal(world.reload().status, 'pr-open');
    assert.equal(world.reload().lastError, null);
  });

  it('fails at the pull request stage when the undraft is refused', async () => {
    const world = new World();
    const opener = new FakeOpener();
    opener.readyFailure = new GithubApiError('github_forbidden', 'no write access', 403);
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      opener,
    );

    await delivery.complete(world.session, world.stories());

    const failed = world.reload();
    assert.equal(failed.status, 'failed');
    assert.equal(failed.failureStage, 'pull_request');
    assert.equal(failed.prUrl, 'https://github.com/acme/demo/pull/7', 'the link survives');
    assert.match(failed.lastError ?? '', /marked ready for review/);
  });

  it('adopts an existing pull request without failing', async () => {
    const world = new World();
    const opener = new FakeOpener();
    opener.adopted = true;
    opener.url = 'https://github.com/acme/demo/pull/4';
    const delivery = createDeliveryService(world.config, world.db, world.containers, world.exec, opener);

    const result = await delivery.retry(world.session.id).catch(() => null);
    // A building session cannot be retried; deliver through the loop's seam.
    assert.equal(result, null);

    await delivery.complete(world.session, world.stories());
    assert.equal(world.reload().prUrl, 'https://github.com/acme/demo/pull/4');
    assert.equal(world.reload().status, 'pr-open');
  });

  it('fails the session with git stderr when the push is rejected', async () => {
    const world = new World();
    world.push = {
      exitCode: 1,
      stdout: '',
      stderr: '! [rejected] chief/add-login -> chief/add-login (fetch first)',
      timedOut: false,
    };
    const opener = new FakeOpener();
    const delivery = createDeliveryService(world.config, world.db, world.containers, world.exec, opener);

    await delivery.complete(world.session, world.stories());

    const failed = world.reload();
    assert.equal(failed.status, 'failed');
    assert.match(failed.lastError ?? '', /Pushing "chief\/add-login" to origin failed/);
    assert.match(failed.lastError ?? '', /\[rejected\]/);
    assert.equal(opener.calls.length, 0, 'no pull request is attempted after a failed push');
  });

  it('fails the session with GitHub’s own message when the pull request is refused', async () => {
    const world = new World();
    const opener = new FakeOpener();
    opener.failure = new GithubApiError(
      'github_rejected',
      'GitHub rejected the request: No commits between develop and chief/add-login',
      422,
    );
    const delivery = createDeliveryService(world.config, world.db, world.containers, world.exec, opener);

    await delivery.complete(world.session, world.stories());

    const failed = world.reload();
    assert.equal(failed.status, 'failed');
    assert.match(failed.lastError ?? '', /No commits between develop and chief\/add-login/);
  });

  it('fails when there is no token, and says the branch was pushed anyway', async () => {
    const world = new World();
    setSetting(world.db, 'github_token', '');
    world.db.prepare("DELETE FROM settings WHERE key = 'github_token'").run();
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      new FakeOpener(),
    );

    await delivery.complete(world.session, world.stories());
    const failed = world.reload();
    assert.equal(failed.status, 'failed');
    assert.match(failed.lastError ?? '', /branch was pushed, but no GitHub token is configured/);
  });

  it('refuses a repository whose slug is not owner/repo', async () => {
    const world = new World({ slug: 'not a slug' });
    const opener = new FakeOpener();
    const delivery = createDeliveryService(world.config, world.db, world.containers, world.exec, opener);

    await delivery.complete(world.session, world.stories());
    assert.equal(opener.calls.length, 0);
    assert.match(world.reload().lastError ?? '', /is not a GitHub owner\/repo slug/);
  });

  it('fails with the reason when the session container cannot be started', async () => {
    const world = new World();
    world.containerFailure = new Error('Cannot connect to the Docker daemon');
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      new FakeOpener(),
    );

    await delivery.complete(world.session, world.stories());
    assert.match(world.reload().lastError ?? '', /Cannot connect to the Docker daemon/);
    assert.equal(world.reload().status, 'failed');
  });
});

describe('pushing after each completed story', () => {
  it('pushes without touching the session, so the build is never ended by it', async () => {
    const world = new World();
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      new FakeOpener(),
    );

    await delivery.push(world.session);
    assert.equal(world.execs.length, 1);
    assert.equal(world.reload().status, 'building');
  });

  it('swallows a failed push: the commits are safe locally', async () => {
    const world = new World();
    world.push = { exitCode: 128, stdout: '', stderr: 'fatal: could not read from remote', timedOut: false };
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      new FakeOpener(),
    );

    await delivery.push(world.session);
    const unchanged = world.reload();
    assert.equal(unchanged.status, 'building');
    assert.equal(unchanged.lastError, null);
  });

  it('swallows an unreachable daemon too', async () => {
    const world = new World();
    world.containerFailure = new Error('no daemon');
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      new FakeOpener(),
    );

    await delivery.push(world.session);
    assert.equal(world.reload().status, 'building');
  });
});

describe('retrying a delivery', () => {
  function serviceFor(world: World, opener: PullRequestOpener) {
    return createDeliveryService(world.config, world.db, world.containers, world.exec, opener);
  }

  it('re-attempts only the push and the pull request', async () => {
    const world = new World();
    updateSession(world.db, world.session.id, { status: 'failed', lastError: 'push failed' });
    const opener = new FakeOpener();

    const result = await serviceFor(world, opener).retry(world.session.id);

    assert.equal(result.ok, true);
    assert.equal(result.prUrl, 'https://github.com/acme/demo/pull/7');
    assert.equal(world.execs.length, 1, 'exactly one command ran: the push');
    assert.equal(opener.calls.length, 1);
    assert.equal(world.reload().status, 'pr-open');
    assert.equal(world.reload().lastError, null);
  });

  it('ends a retried pull_request failure in pr-open, not finished', async () => {
    const world = new World();
    const opener = new FakeOpener();
    opener.failure = new GithubApiError('github_rejected', 'GitHub is having a moment', 500);
    const delivery = serviceFor(world, opener);

    await delivery.complete(world.session, world.stories());
    const failed = world.reload();
    assert.equal(failed.status, 'failed');
    assert.equal(failed.failureStage, 'pull_request');

    // The same session, retried once GitHub answers: the delivery that opens
    // the pull request lands in `pr-open` whether it is the first attempt or
    // the fifth.
    opener.failure = null;
    const result = await delivery.retry(world.session.id);

    assert.equal(result.ok, true);
    assert.equal(result.status, 'pr-open');
    const delivered = world.reload();
    assert.equal(delivered.status, 'pr-open');
    assert.equal(delivered.prUrl, 'https://github.com/acme/demo/pull/7');
    assert.equal(delivered.failureStage, null);
    assert.equal(delivered.lastError, null);
  });

  it('reports a failure as an answer, not as a failed request', async () => {
    const world = new World();
    updateSession(world.db, world.session.id, { status: 'failed' });
    world.push = { exitCode: 1, stdout: '', stderr: 'Permission denied (publickey).', timedOut: false };

    const result = await serviceFor(world, new FakeOpener()).retry(world.session.id);
    assert.equal(result.ok, false);
    assert.equal(result.code, 'push_failed');
    assert.match(result.stderr, /Permission denied/);
    assert.equal(world.reload().status, 'failed');
  });

  it('refuses while the session is still building', async () => {
    const world = new World();
    const failure = await serviceFor(world, new FakeOpener())
      .retry(world.session.id)
      .catch((cause: unknown) => cause);
    assert.ok(failure instanceof DeliveryError);
    assert.equal(failure.status, 409);
    assert.equal(failure.code, 'session_is_building');
  });

  it('refuses while a story is still outstanding', async () => {
    const world = new World();
    updateSession(world.db, world.session.id, { status: 'failed' });
    syncStories(world.db, world.session.id, [
      { storyId: 'US-001', title: 'First', priority: 1, status: 'done' },
      { storyId: 'US-002', title: 'Second', priority: 2, status: 'todo' },
    ]);

    const failure = await serviceFor(world, new FakeOpener())
      .retry(world.session.id)
      .catch((cause: unknown) => cause);
    assert.ok(failure instanceof DeliveryError);
    assert.equal(failure.code, 'session_not_complete');
    assert.match(failure.message, /1 of 2 stories/);
  });

  it('is 404 for a session that no longer exists', async () => {
    const world = new World();
    const failure = await serviceFor(world, new FakeOpener())
      .retry('nope')
      .catch((cause: unknown) => cause);
    assert.ok(failure instanceof DeliveryError);
    assert.equal(failure.status, 404);
  });
});

/** A review pass the test scripts, one outcome per attempt. */
class FakeReviewer implements SessionReviewer {
  calls = 0;
  /** Consumed one per attempt; the last one repeats for every attempt after. */
  outcomes: ReviewPassResult[] = [reviewPass()];

  review(session: Session): Promise<ReviewPassResult> {
    this.calls += 1;
    const outcome =
      this.outcomes[Math.min(this.calls - 1, this.outcomes.length - 1)] ?? reviewPass();
    return Promise.resolve({ ...outcome, sessionId: session.id });
  }
}

/** A {@link ReviewPublisher} the test scripts the same way. */
class FakePublisher implements ReviewPublisher {
  readonly calls: { token: string; target: ReviewTarget; report: ReviewReport }[] = [];
  /** Consumed one per call; the last one repeats. `null` is a success. */
  failures: (Error | null)[] = [null];

  publish(token: string, target: ReviewTarget, report: ReviewReport): Promise<PublishedReview> {
    this.calls.push({ token, target, report });
    const failure = this.failures[Math.min(this.calls.length - 1, this.failures.length - 1)] ?? null;
    if (failure !== null) return Promise.reject(failure);
    return Promise.resolve({
      url: 'https://github.com/acme/demo/pull/7#pullrequestreview-1',
      inlineComments: report.findings.length,
      foldedFindings: 0,
    });
  }
}

function reviewPass(findings = 1): ReviewPassResult {
  return {
    ok: true,
    sessionId: 's',
    code: 'ok',
    message: 'The review found something to comment on.',
    report: {
      summary: 'Two files changed; one thing worth a look.',
      findings: Array.from({ length: findings }, (_unused, index) => ({
        path: 'src/index.ts',
        line: index + 1,
        body: 'This can be null here.',
      })),
    },
    output: '',
  };
}

function reviewFailure(code: ReviewPassResult['code'], message: string): ReviewPassResult {
  return { ok: false, sessionId: 's', code, message, report: null, output: '' };
}

describe('the code review of a delivery', () => {
  function serviceFor(world: World, opener: PullRequestOpener, step: ReviewStep) {
    return createDeliveryService(world.config, world.db, world.containers, world.exec, opener, step);
  }

  /** The session as the build loop hands it over, with the flag on. */
  function reviewedSession(world: World): Session {
    return updateSession(world.db, world.session.id, { codeReview: true }) ?? (undefined as never);
  }

  it('does not review a session with the flag off', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    const publisher = new FakePublisher();
    const delivery = serviceFor(world, new FakeOpener(), new ReviewStep(reviewer, publisher));

    await delivery.complete(world.session, world.stories());

    assert.equal(reviewer.calls, 0, 'no review is run for a session that did not ask for one');
    assert.equal(publisher.calls.length, 0);
    const finished = world.reload();
    assert.equal(finished.status, 'pr-open');
    assert.equal(finished.prUrl, 'https://github.com/acme/demo/pull/7');
    assert.equal(finished.lastError, null);
  });

  it('puts the session in reviewing while the draft pull request is reviewed', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    const opener = new FakeOpener();
    const seen: (SessionStatus | undefined)[] = [];
    const publisher = new FakePublisher();
    // Reading the row rather than the handed-over object: the status write is
    // the point, and the object the step was called with is a snapshot.
    const watcher: SessionReviewer = {
      review: (session) => {
        seen.push(getSession(world.db, session.id)?.status);
        return reviewer.review(session);
      },
    };
    const delivery = serviceFor(world, opener, new ReviewStep(watcher, publisher));

    await delivery.complete(reviewedSession(world), world.stories());

    assert.deepEqual(seen, ['reviewing'], 'the review runs with the session in reviewing');
    // The pull request URL is stored before the review, and the undraft waits
    // until the review is posted (US-003).
    assert.equal(publisher.calls.length, 1);
    assert.deepEqual(opener.ready, [{ token: TOKEN, pullRequestId: 'PR_kwDO7' }]);
    const finished = world.reload();
    assert.equal(finished.status, 'pr-open');
    assert.equal(finished.prUrl, 'https://github.com/acme/demo/pull/7');
  });

  it('leaves a session the sync merged mid-review merged (US-007)', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    const opener = new FakeOpener();
    // Somebody merges the draft from GitHub while the review runs, and the
    // pull request sync writes that down before the delivery is finished.
    const watcher: SessionReviewer = {
      review: (session) => {
        updateSession(world.db, session.id, { status: 'merged' });
        return reviewer.review(session);
      },
    };
    const delivery = serviceFor(world, opener, new ReviewStep(watcher, new FakePublisher()));

    await delivery.complete(reviewedSession(world), world.stories());

    // GitHub's answer stands: the delivery does not put the session back into
    // pr-open behind a pull request that is already in the base branch.
    const row = world.reload();
    assert.equal(row.status, 'merged');
    assert.equal(row.prUrl, 'https://github.com/acme/demo/pull/7');
    // The pull request was still released before the sync took over.
    assert.deepEqual(opener.ready, [{ token: TOKEN, pullRequestId: 'PR_kwDO7' }]);
  });

  it('does not fail a session the sync merged mid-review (US-007)', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewFailure('agent_failed', 'the agent died')];
    const opener = new FakeOpener();
    const watcher: SessionReviewer = {
      review: (session) => {
        updateSession(world.db, session.id, { status: 'merged' });
        return reviewer.review(session);
      },
    };
    const delivery = serviceFor(world, opener, new ReviewStep(watcher, new FakePublisher()));

    await delivery.complete(reviewedSession(world), world.stories());

    const row = world.reload();
    // The review really did fail, but a merged pull request is not a thing to
    // retry, so the failure is reported and not written.
    assert.equal(row.status, 'merged');
    assert.equal(row.failureStage, null);
  });

  it('stores the pull request URL, and undrafts before failing at the review', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewFailure('agent_failed', 'the agent died')];
    const opener = new FakeOpener();
    const delivery = serviceFor(world, opener, new ReviewStep(reviewer, new FakePublisher()));

    await delivery.complete(reviewedSession(world), world.stories());

    const failed = world.reload();
    assert.equal(failed.status, 'failed');
    assert.equal(failed.failureStage, 'review');
    assert.equal(failed.prUrl, 'https://github.com/acme/demo/pull/7');
    // A review that has spent its three attempts is not coming back, so the
    // pull request is released rather than stranded as a draft (US-006).
    assert.deepEqual(opener.ready, [{ token: TOKEN, pullRequestId: 'PR_kwDO7' }]);
  });

  it('keeps the session failed at the review when the undraft fails too', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewFailure('agent_failed', 'the agent died')];
    const opener = new FakeOpener();
    opener.readyFailure = new GithubApiError('github_error', 'GitHub is having a moment.');
    const delivery = serviceFor(world, opener, new ReviewStep(reviewer, new FakePublisher()));

    await delivery.complete(reviewedSession(world), world.stories());

    const failed = world.reload();
    // The review is the root cause and the stage a retry re-runs; the undraft
    // it could not do is reported in the same message and attempted again.
    assert.equal(failed.failureStage, 'review');
    assert.match(failed.lastError ?? '', /could not be marked ready for review/);
  });

  it('reviews the pull request it just opened, then finishes the session', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    const publisher = new FakePublisher();
    const delivery = serviceFor(world, new FakeOpener(), new ReviewStep(reviewer, publisher));

    const result = await delivery.retry(reviewedSession(world).id).catch(() => null);
    assert.equal(result, null, 'a building session is delivered through the loop’s seam');
    await delivery.complete(reviewedSession(world), world.stories());

    assert.equal(reviewer.calls, 1);
    assert.equal(publisher.calls.length, 1);
    assert.equal(publisher.calls[0]?.token, TOKEN);
    assert.deepEqual(publisher.calls[0]?.target, { slug: 'acme/demo', number: 7 });
    const finished = world.reload();
    assert.equal(finished.status, 'pr-open');
    assert.equal(finished.prUrl, 'https://github.com/acme/demo/pull/7');
    assert.equal(finished.lastError, null);
  });

  it('retries a failed attempt and finishes on the second', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [
      reviewFailure('agent_timed_out', 'The review agent ran out of time.'),
      reviewPass(),
    ];
    const publisher = new FakePublisher();
    const opener = new FakeOpener();
    const delivery = serviceFor(world, opener, new ReviewStep(reviewer, publisher));

    await delivery.complete(reviewedSession(world), world.stories());

    assert.equal(reviewer.calls, 2);
    assert.equal(publisher.calls.length, 1, 'only the attempt that produced findings posted');
    assert.equal(world.reload().status, 'pr-open');
    assert.equal(world.reload().lastError, null);
    // The half of the delivery that already worked is not repeated by a retry.
    assert.equal(world.execs.length, 1, 'exactly one push');
    assert.equal(opener.calls.length, 1, 'exactly one pull request');
  });

  it('retries a GitHub posting error too', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    const publisher = new FakePublisher();
    publisher.failures = [new GithubApiError('github_unreachable', 'GitHub is unreachable.', 0), null];
    const delivery = serviceFor(world, new FakeOpener(), new ReviewStep(reviewer, publisher));

    await delivery.complete(reviewedSession(world), world.stories());

    assert.equal(reviewer.calls, 2, 'a posting failure costs a whole attempt, review included');
    assert.equal(publisher.calls.length, 2);
    assert.equal(world.reload().status, 'pr-open');
  });

  it('fails the session at the review stage after three attempts, keeping the pull request', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewFailure('invalid_findings', 'The findings could not be read.')];
    const publisher = new FakePublisher();
    const opener = new FakeOpener();
    const delivery = serviceFor(world, opener, new ReviewStep(reviewer, publisher));

    const result = await delivery.complete(reviewedSession(world), world.stories());
    assert.equal(result, undefined, 'the loop’s hand-off answers nothing');

    assert.equal(reviewer.calls, 3, 'three attempts, then no more');
    assert.equal(publisher.calls.length, 0);
    const failed = world.reload();
    assert.equal(failed.status, 'failed');
    assert.equal(failed.failureStage, 'review');
    assert.match(failed.lastError ?? '', /failed after 3 attempts/);
    assert.match(failed.lastError ?? '', /The findings could not be read\./);
    assert.equal(failed.prUrl, 'https://github.com/acme/demo/pull/7', 'the pull request is kept');
    assert.equal(world.execs.length, 1, 'the push was not repeated');
    assert.equal(opener.calls.length, 1, 'the pull request was not opened again');
  });

  it('holds the session on the usage limit instead of failing it', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewFailure('usage_limit', 'The review agent stopped on a usage limit.')];
    const opener = new FakeOpener();
    const delivery = serviceFor(world, opener, new ReviewStep(reviewer, new FakePublisher()));

    await delivery.complete(reviewedSession(world), world.stories());

    assert.equal(reviewer.calls, 1, 'a second attempt walks into the same wall');
    const held = world.reload();
    // The account is out, not the review: the session waits for the hold and
    // resumes into the same chain, so the pull request stays a draft (US-006).
    assert.equal(held.status, 'waiting');
    assert.equal(held.failureStage, null);
    assert.notEqual(held.waitingUntil, null);
    assert.equal(new UsageLimitHold(world.db).active(), true, 'agent work is held');
    assert.match(held.lastError ?? '', /usage limit/);
    assert.equal(opener.ready.length, 0, 'the review it is waiting for has not happened');
    assert.equal(held.prUrl, 'https://github.com/acme/demo/pull/7');
  });

  it('posts a review that found nothing, then undrafts and finishes the session', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewPass(0)];
    const publisher = new FakePublisher();
    const opener = new FakeOpener();
    const solver = new FakeSolver();
    // Both halves record into the same list: what must never happen is a pull
    // request announced as ready before the review it is waiting for is up
    // (US-004).
    const order: string[] = [];
    const seen: (SessionStatus | undefined)[] = [];
    const watchedPublisher: ReviewPublisher = {
      publish: (token, target, report) => {
        seen.push(getSession(world.db, world.session.id)?.status);
        order.push('publish');
        return publisher.publish(token, target, report);
      },
    };
    const watchedOpener: PullRequestOpener = {
      open: (token, input) => opener.open(token, input),
      find: (token, input) => opener.find(token, input),
      markReady: (token, pullRequestId) => {
        order.push('markReady');
        return opener.markReady(token, pullRequestId);
      },
    };
    const delivery = serviceFor(
      world,
      watchedOpener,
      new ReviewStep(reviewer, watchedPublisher, () => solver),
    );

    await delivery.complete(reviewedSession(world), world.stories());

    assert.deepEqual(order, ['publish', 'markReady'], 'the comment is up before the undraft');
    assert.deepEqual(seen, ['reviewing'], 'the review is posted with the session still reviewing');
    assert.equal(publisher.calls.length, 1);
    assert.deepEqual(publisher.calls[0]?.report.findings, []);
    assert.equal(solver.calls.length, 0, 'nothing was flagged, so no feedback run is started');
    assert.deepEqual(opener.ready, [{ token: TOKEN, pullRequestId: 'PR_kwDO7' }]);
    const finished = world.reload();
    assert.equal(finished.status, 'pr-open');
    assert.equal(finished.failureStage, null);
    assert.equal(finished.lastError, null);
  });
});

/** The PR-feedback solver, scripted: it starts a run or refuses like the real one. */
class FakeSolver implements FeedbackSolver {
  readonly calls: { repositoryId: string; prNumber: number }[] = [];
  /** What `start` rejects with; `null` starts a run. */
  refusal: Error | null = null;
  /**
   * Answers in place of the canned id, for a test that needs a real `pr_runs`
   * row to move. The real service answers as soon as the row says `running`
   * and drives the rest of the pass afterwards.
   */
  run: ((repositoryId: string, prNumber: number) => Promise<{ id: string }>) | null = null;

  start(repositoryId: string, prNumber: number): Promise<{ id: string }> {
    this.calls.push({ repositoryId, prNumber });
    if (this.refusal !== null) return Promise.reject(this.refusal);
    if (this.run !== null) return this.run(repositoryId, prNumber);
    return Promise.resolve({ id: 'run-1' });
  }
}

/** A `pr_runs` row in `running`, as `PrFeedbackService.start` leaves one. */
function startedRun(world: World, repositoryId: string, prNumber: number): string {
  const run = createPrRun(world.db, {
    repositoryId,
    prNumber,
    prUrl: `https://github.com/acme/demo/pull/${String(prNumber)}`,
    prTitle: 'add-login',
    headBranch: 'chief/add-login',
    baseBranch: 'develop',
  });
  updatePrRun(world.db, run.id, { status: 'running' });
  return run.id;
}

/** Polls `predicate` for a moment; the wait under test is a poll of its own. */
async function until(predicate: () => boolean, what: string): Promise<void> {
  for (let attempt = 0; attempt < 500; attempt += 1) {
    if (predicate()) return;
    await new Promise((resolve) => setTimeout(resolve, 2));
  }
  assert.fail(`timed out waiting for ${what}`);
}

describe('chaining into the pull request feedback solver', () => {
  function serviceFor(world: World, step: ReviewStep, opener: PullRequestOpener = new FakeOpener()) {
    return createDeliveryService(world.config, world.db, world.containers, world.exec, opener, step);
  }

  /** The session as the build loop hands it over, with the flag on. */
  function reviewedSession(world: World): Session {
    return updateSession(world.db, world.session.id, { codeReview: true }) ?? (undefined as never);
  }

  it('starts a run on the reviewed pull request once the findings are posted', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewPass(2)];
    const solver = new FakeSolver();
    const delivery = serviceFor(
      world,
      new ReviewStep(reviewer, new FakePublisher(), () => solver),
    );

    const result = await delivery.retry(reviewedSession(world).id).catch(() => null);
    assert.equal(result, null, 'a building session is delivered through the loop’s seam');
    await delivery.complete(reviewedSession(world), world.stories());

    assert.deepEqual(solver.calls, [{ repositoryId: world.session.repositoryId, prNumber: 7 }]);
    const finished = world.reload();
    assert.equal(finished.status, 'pr-open');
    assert.equal(finished.lastError, null);
  });

  it('does not start a run when the review found nothing to solve', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewPass(0)];
    const solver = new FakeSolver();
    const opener = new FakeOpener();

    await serviceFor(
      world,
      new ReviewStep(reviewer, new FakePublisher(), () => solver),
      opener,
    ).complete(reviewedSession(world), world.stories());

    assert.equal(solver.calls.length, 0, 'there is nothing on the pull request to work on');
    // Nothing is waited for, so the draft is released as part of this delivery.
    assert.deepEqual(opener.ready, [{ token: TOKEN, pullRequestId: 'PR_kwDO7' }]);
    assert.equal(world.reload().status, 'pr-open');
  });

  it('undrafts and fails at the feedback stage when the solver refuses the run', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    const opener = new FakeOpener();
    const solver = new FakeSolver();
    solver.refusal = new PrFeedbackError(
      409,
      'no_free_slot',
      'Every build slot is in use. Wait for one to free, or raise the cap on the settings page.',
    );

    const result = await serviceFor(
      world,
      new ReviewStep(reviewer, new FakePublisher(), () => solver),
      opener,
    ).complete(reviewedSession(world), world.stories());

    assert.equal(result, undefined, 'the loop’s hand-off answers nothing either way');
    assert.equal(solver.calls.length, 1);
    const failed = world.reload();
    // The findings are on the pull request with nothing coming to fix them, so
    // the pull request is released and the stage is one a retry re-runs.
    assert.deepEqual(opener.ready, [{ token: TOKEN, pullRequestId: 'PR_kwDO7' }]);
    assert.equal(failed.status, 'failed');
    assert.equal(failed.failureStage, 'feedback');
    assert.equal(isDeliveryStage(failed.failureStage), true);
    assert.match(failed.lastError ?? '', /Every build slot is in use\./);
  });

  it('reports the refusal the way the PullRequests page would', async () => {
    const world = new World();
    failedAtReviewFor(world);
    const solver = new FakeSolver();
    solver.refusal = new PrFeedbackError(409, 'no_free_slot', 'Every build slot is in use.');

    const result = await serviceFor(
      world,
      new ReviewStep(new FakeReviewer(), new FakePublisher(), () => solver),
    ).retry(world.session.id);

    assert.equal(result.ok, false, 'a run that never started is the retry’s outcome');
    assert.equal(result.code, 'feedback_failed');
    assert.match(result.message, /Every build slot is in use\./);
  });

  /**
   * The whole point of US-005: the findings are fixed and answered while the
   * pull request is still a draft, so nobody is told it is ready to read
   * half-way through the run that is changing it.
   */
  it('holds the draft in `fixing` until the feedback run reaches a terminal status', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewPass(2)];
    const opener = new FakeOpener();
    const order: string[] = [];
    const solver = new FakeSolver();
    const started: { settle: ((status: PrRunStatus) => void) | null } = { settle: null };
    solver.run = (repositoryId, prNumber) => {
      const runId = startedRun(world, repositoryId, prNumber);
      started.settle = (status) => {
        order.push('feedback');
        updatePrRun(world.db, runId, { status });
      };
      return Promise.resolve({ id: runId });
    };
    const publisher = new FakePublisher();
    const watchedPublisher: ReviewPublisher = {
      publish: (token, target, report) => {
        order.push('publish');
        return publisher.publish(token, target, report);
      },
    };
    const watchedOpener: PullRequestOpener = {
      open: (token, input) => opener.open(token, input),
      find: (token, input) => opener.find(token, input),
      markReady: (token, pullRequestId) => {
        order.push('markReady');
        return opener.markReady(token, pullRequestId);
      },
    };
    const delivery = createDeliveryService(
      { ...world.config, feedbackRunPollMs: 1 },
      world.db,
      world.containers,
      world.exec,
      watchedOpener,
      new ReviewStep(reviewer, watchedPublisher, () => solver),
    );

    const delivered = delivery.complete(reviewedSession(world), world.stories());
    await until(() => world.reload().status === 'fixing', 'the session to reach fixing');
    assert.deepEqual(order, ['publish'], 'the review is up and the run is being waited for');
    assert.deepEqual(opener.ready, [], 'the pull request is still a draft');

    assert.ok(started.settle, 'the feedback run was started');
    started.settle('finished');
    await delivered;

    assert.deepEqual(order, ['publish', 'feedback', 'markReady'], 'the fix lands before the undraft');
    assert.deepEqual(opener.ready, [{ token: TOKEN, pullRequestId: 'PR_kwDO7' }]);
    assert.equal(reviewer.calls, 1, 'one review, one fix pass, and no re-review');
    const finished = world.reload();
    assert.equal(finished.status, 'pr-open');
    assert.equal(finished.failureStage, null);
    assert.equal(finished.lastError, null);
  });

  it('stops waiting when the feedback run fails, and still undrafts', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewPass(1)];
    const opener = new FakeOpener();
    const solver = new FakeSolver();
    solver.run = (repositoryId, prNumber) => {
      const runId = startedRun(world, repositoryId, prNumber);
      updatePrRun(world.db, runId, { status: 'failed', failureStage: 'push', lastError: 'no' });
      return Promise.resolve({ id: runId });
    };

    const delivery = createDeliveryService(
      { ...world.config, feedbackRunPollMs: 1 },
      world.db,
      world.containers,
      world.exec,
      opener,
      new ReviewStep(reviewer, new FakePublisher(), () => solver),
    );
    await delivery.complete(reviewedSession(world), world.stories());

    // Released first, failed second: the fixes did not land, but the pull
    // request is a human's to read either way (US-006).
    assert.deepEqual(opener.ready, [{ token: TOKEN, pullRequestId: 'PR_kwDO7' }]);
    const failed = world.reload();
    assert.equal(failed.status, 'failed');
    assert.equal(failed.failureStage, 'feedback');
    assert.match(failed.lastError ?? '', /feedback run failed at the push/);
  });

  it('undrafts straight away when the run is refused for having nothing to fix', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewPass(1)];
    const opener = new FakeOpener();
    const solver = new FakeSolver();
    // Every finding was folded into the review body, so there is no unresolved
    // thread to answer and nothing to wait for.
    solver.refusal = new PrFeedbackError(
      409,
      'no_unresolved_feedback',
      'There is no unresolved review feedback on that pull request.',
    );

    await serviceFor(
      world,
      new ReviewStep(reviewer, new FakePublisher(), () => solver),
      opener,
    ).complete(reviewedSession(world), world.stories());

    assert.equal(solver.calls.length, 1);
    assert.deepEqual(opener.ready, [{ token: TOKEN, pullRequestId: 'PR_kwDO7' }]);
    const finished = world.reload();
    assert.equal(finished.status, 'pr-open');
    assert.equal(finished.failureStage, null);
    assert.equal(finished.lastError, null);
  });

  it('starts nothing when the review never posted', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewFailure('invalid_findings', 'The findings could not be read.')];
    const solver = new FakeSolver();

    await serviceFor(world, new ReviewStep(reviewer, new FakePublisher(), () => solver)).complete(
      reviewedSession(world),
      world.stories(),
    );

    assert.equal(solver.calls.length, 0, 'there are no findings on the pull request');
    assert.equal(world.reload().failureStage, 'review');
  });
});

/** A session parked exactly where a review retry picks it up. */
function failedAtReviewFor(world: World): void {
  updateSession(world.db, world.session.id, {
    status: 'failed',
    failureStage: 'review',
    lastError: 'The code review failed after 3 attempts.',
    prUrl: 'https://github.com/acme/demo/pull/7',
    codeReview: true,
  });
}

describe('retrying a session that failed at the review', () => {
  function failedAtReview(world: World, codeReview = true): void {
    updateSession(world.db, world.session.id, {
      status: 'failed',
      failureStage: 'review',
      lastError: 'The code review failed after 3 attempts.',
      prUrl: 'https://github.com/acme/demo/pull/7',
      codeReview,
    });
  }

  function serviceFor(world: World, opener: PullRequestOpener, step: ReviewStep) {
    return createDeliveryService(world.config, world.db, world.containers, world.exec, opener, step);
  }

  it('re-runs the review only, and finishes the session', async () => {
    const world = new World();
    failedAtReview(world);
    const reviewer = new FakeReviewer();
    const publisher = new FakePublisher();
    const opener = new FakeOpener();

    const result = await serviceFor(world, opener, new ReviewStep(reviewer, publisher)).retry(
      world.session.id,
    );

    assert.equal(result.ok, true);
    assert.equal(result.prUrl, 'https://github.com/acme/demo/pull/7');
    assert.equal(world.execs.length, 0, 'nothing was pushed again');
    assert.equal(opener.calls.length, 0, 'the pull request was not opened again');
    assert.equal(reviewer.calls, 1);
    assert.deepEqual(publisher.calls[0]?.target, { slug: 'acme/demo', number: 7 });
    const finished = world.reload();
    assert.equal(finished.status, 'pr-open');
    assert.equal(finished.failureStage, null);
    assert.equal(finished.lastError, null);
  });

  it('waits for the retried review’s feedback run, then looks the pull request up and undrafts it', async () => {
    const world = new World();
    failedAtReview(world);
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewPass(1)];
    const opener = new FakeOpener();
    const solver = new FakeSolver();
    const order: string[] = [];
    const holder: { settle: (() => void) | null } = { settle: null };
    solver.run = (repositoryId, prNumber) => {
      const runId = startedRun(world, repositoryId, prNumber);
      order.push('feedback');
      holder.settle = () => {
        updatePrRun(world.db, runId, { status: 'finished' });
      };
      return Promise.resolve({ id: runId });
    };
    const watchedOpener: PullRequestOpener = {
      open: (token, input) => opener.open(token, input),
      find: (token, input) => {
        order.push('find');
        return opener.find(token, input);
      },
      markReady: (token, pullRequestId) => {
        order.push('markReady');
        return opener.markReady(token, pullRequestId);
      },
    };
    const delivery = createDeliveryService(
      { ...world.config, feedbackRunPollMs: 1 },
      world.db,
      world.containers,
      world.exec,
      watchedOpener,
      new ReviewStep(reviewer, new FakePublisher(), () => solver),
    );

    const retried = delivery.retry(world.session.id);
    // The retry has no node id of its own, so it may not undraft before the
    // run it started is over: the session sits in `fixing` until it is.
    await until(() => world.reload().status === 'fixing', 'the retry to start fixing');
    assert.deepEqual(opener.ready, [], 'nothing is released while the fixes are in flight');
    holder.settle?.();

    const result = await retried;
    assert.equal(result.ok, true);
    assert.deepEqual(order, ['feedback', 'find', 'markReady'], 'the wait comes before the undraft');
    assert.deepEqual(opener.lookups, [
      { token: TOKEN, input: { slug: 'acme/demo', head: 'chief/add-login', base: 'develop' } },
    ]);
    assert.deepEqual(opener.ready, [{ token: TOKEN, pullRequestId: 'PR_kwDO7' }]);
    const finished = world.reload();
    assert.equal(finished.status, 'pr-open');
    assert.equal(finished.failureStage, null);
  });

  it('fails the retry at the pull request stage when the undraft is refused', async () => {
    const world = new World();
    failedAtReview(world);
    const opener = new FakeOpener();
    opener.readyFailure = new GithubApiError('github_forbidden', 'This token cannot write here.');

    const result = await serviceFor(
      world,
      opener,
      new ReviewStep(new FakeReviewer(), new FakePublisher()),
    ).retry(world.session.id);

    assert.equal(result.ok, false);
    assert.equal(result.code, 'pull_request_failed');
    const failed = world.reload();
    assert.equal(failed.failureStage, 'pull_request');
    assert.match(failed.lastError ?? '', /could not be marked ready for review/);
  });

  it('finishes the retry when the pull request is no longer open to undraft', async () => {
    const world = new World();
    failedAtReview(world);
    const opener = new FakeOpener();
    // Merged or closed while the review was failing: there is no draft left to
    // release, and that is not something to fail a session over.
    opener.open_ = false;

    const result = await serviceFor(
      world,
      opener,
      new ReviewStep(new FakeReviewer(), new FakePublisher()),
    ).retry(world.session.id);

    assert.equal(result.ok, true);
    assert.deepEqual(opener.ready, []);
    assert.equal(world.reload().status, 'pr-open');
  });

  it('undrafts before failing again when the retried review also fails', async () => {
    const world = new World();
    failedAtReview(world);
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewFailure('agent_failed', 'The review agent exited with code 1.')];
    const opener = new FakeOpener();

    const result = await serviceFor(
      world,
      opener,
      new ReviewStep(reviewer, new FakePublisher()),
    ).retry(world.session.id);

    assert.equal(result.code, 'review_failed');
    assert.deepEqual(opener.ready, [{ token: TOKEN, pullRequestId: 'PR_kwDO7' }]);
    assert.equal(world.reload().failureStage, 'review');
  });

  it('holds the retry on the usage limit, leaving the pull request a draft', async () => {
    const world = new World();
    failedAtReview(world);
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewFailure('usage_limit', 'The review agent stopped on a usage limit.')];
    const opener = new FakeOpener();

    const result = await serviceFor(
      world,
      opener,
      new ReviewStep(reviewer, new FakePublisher()),
    ).retry(world.session.id);

    assert.equal(result.ok, false);
    assert.equal(result.code, 'usage_limit_hold');
    const held = world.reload();
    assert.equal(held.status, 'waiting');
    assert.equal(held.failureStage, null);
    assert.equal(opener.ready.length, 0);
  });

  it('gives the retry its own three attempts before failing again', async () => {
    const world = new World();
    failedAtReview(world);
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewFailure('agent_failed', 'The review agent exited with code 1.')];
    const opener = new FakeOpener();

    const result = await serviceFor(world, opener, new ReviewStep(reviewer, new FakePublisher())).retry(
      world.session.id,
    );

    assert.equal(result.ok, false);
    assert.equal(result.code, 'review_failed');
    assert.equal(reviewer.calls, 3);
    assert.equal(world.execs.length, 0);
    assert.equal(opener.calls.length, 0);
    const failed = world.reload();
    assert.equal(failed.status, 'failed');
    assert.equal(failed.failureStage, 'review');
    assert.equal(failed.prUrl, 'https://github.com/acme/demo/pull/7');
  });

  it('just finishes the session when the review was switched off since', async () => {
    const world = new World();
    failedAtReview(world, false);
    const reviewer = new FakeReviewer();

    const result = await serviceFor(world, new FakeOpener(), new ReviewStep(reviewer, new FakePublisher()))
      .retry(world.session.id);

    assert.equal(result.ok, true);
    assert.equal(reviewer.calls, 0);
    assert.equal(world.reload().status, 'pr-open');
  });

  it('delivers in full when the failed session has no pull request URL', async () => {
    const world = new World();
    failedAtReview(world);
    updateSession(world.db, world.session.id, { prUrl: null });
    const opener = new FakeOpener();
    const reviewer = new FakeReviewer();

    await serviceFor(world, opener, new ReviewStep(reviewer, new FakePublisher())).retry(
      world.session.id,
    );

    assert.equal(world.execs.length, 1, 'without a pull request there is one to open again');
    assert.equal(opener.calls.length, 1);
    assert.equal(reviewer.calls, 1);
    assert.equal(world.reload().status, 'pr-open');
  });
});

describe('the pull request number in a URL', () => {
  it('reads the number a session stores its pull request as', () => {
    assert.equal(pullRequestNumber('https://github.com/acme/demo/pull/7'), 7);
    assert.equal(pullRequestNumber('https://github.com/acme/demo/pull/1234#issuecomment-1'), 1234);
    assert.equal(pullRequestNumber('https://github.example.com/acme/demo/pull/9/files'), 9);
  });

  it('answers null rather than guessing at anything else', () => {
    assert.equal(pullRequestNumber(null), null);
    assert.equal(pullRequestNumber(''), null);
    assert.equal(pullRequestNumber('https://github.com/acme/demo/pulls'), null);
    assert.equal(pullRequestNumber('https://github.com/acme/demo/pull/abc'), null);
    assert.equal(pullRequestNumber('https://github.com/acme/demo/pull/0'), null);
  });
});

/**
 * US-008: the six ways the draft/undraft chain can end, walked end to end.
 *
 * The individual behaviours are covered above; what this block pins down is the
 * *sequence*. Every case records a trace of the GitHub and review calls
 * together with the session status at that moment, so a change that undrafts
 * too early — before the review is posted, before the feedback run has
 * settled, or before the session is failed — is a failing assertion rather
 * than a behaviour nobody notices.
 */
describe('the draft/undraft chain', () => {
  interface Step {
    /** The call the delivery made. */
    readonly step: 'open' | 'publish' | 'feedback' | 'markReady';
    /** What the session row said at that moment, not what was handed over. */
    readonly status: SessionStatus;
  }

  interface Chain {
    readonly trace: Step[];
    readonly opener: FakeOpener;
    readonly reviewer: FakeReviewer;
    readonly publisher: FakePublisher;
    readonly solver: FakeSolver;
    /** Moves the feedback run the solver started, as the real service would. */
    settle(patch: Parameters<typeof updatePrRun>[2]): void;
    deliver(): Promise<void>;
    session(): Session;
  }

  /**
   * A delivery wired to the file's fakes, with the review step always present:
   * whether it runs is the session's `code_review` flag, exactly as in
   * production. The feedback run is left `running` for the test to settle.
   */
  function chain(
    options: { codeReview?: boolean; findings?: number; review?: ReviewPassResult } = {},
  ): Chain {
    const world = new World();
    const opener = new FakeOpener();
    const reviewer = new FakeReviewer();
    const publisher = new FakePublisher();
    const solver = new FakeSolver();
    const trace: Step[] = [];
    const started: { runId: string | null } = { runId: null };
    const record = (step: Step['step']): void => {
      trace.push({ step, status: getSession(world.db, world.session.id)?.status ?? 'building' });
    };

    reviewer.outcomes = [options.review ?? reviewPass(options.findings ?? 1)];
    solver.run = (repositoryId, prNumber) => {
      started.runId = startedRun(world, repositoryId, prNumber);
      return Promise.resolve({ id: started.runId });
    };
    const tracedOpener: PullRequestOpener = {
      open: (token, input) => {
        record('open');
        return opener.open(token, input);
      },
      find: (token, input) => opener.find(token, input),
      markReady: (token, pullRequestId) => {
        record('markReady');
        return opener.markReady(token, pullRequestId);
      },
    };
    const tracedPublisher: ReviewPublisher = {
      publish: (token, target, report) => {
        record('publish');
        return publisher.publish(token, target, report);
      },
    };
    const delivery = createDeliveryService(
      { ...world.config, feedbackRunPollMs: 1 },
      world.db,
      world.containers,
      world.exec,
      tracedOpener,
      new ReviewStep(reviewer, tracedPublisher, () => solver),
    );
    const session =
      options.codeReview === false
        ? world.session
        : (updateSession(world.db, world.session.id, { codeReview: true }) ?? (undefined as never));

    return {
      trace,
      opener,
      reviewer,
      publisher,
      solver,
      settle: (patch) => {
        assert.ok(started.runId, 'the feedback run was started');
        record('feedback');
        updatePrRun(world.db, started.runId, patch);
      },
      deliver: () => delivery.complete(session, world.stories()),
      session: () => world.reload(),
    };
  }

  it('undrafts straight away when no review will run', async () => {
    const chained = chain({ codeReview: false });

    await chained.deliver();

    // No review means nothing to gate readiness on: open, release, done — and
    // the release is before the session is moved on from `building`.
    assert.deepEqual(chained.trace, [
      { step: 'open', status: 'building' },
      { step: 'markReady', status: 'building' },
    ]);
    assert.equal(chained.reviewer.calls, 0);
    assert.equal(chained.solver.calls.length, 0);
    assert.deepEqual(chained.opener.ready, [{ token: TOKEN, pullRequestId: 'PR_kwDO7' }]);
    const delivered = chained.session();
    assert.equal(delivered.status, 'pr-open');
    assert.equal(delivered.prUrl, 'https://github.com/acme/demo/pull/7');
    assert.equal(delivered.failureStage, null);
  });

  it('undrafts once the review that found nothing is posted', async () => {
    const chained = chain({ findings: 0 });

    await chained.deliver();

    // Nothing was flagged, so there is no feedback run between the comment and
    // the undraft — but the comment is still up first.
    assert.deepEqual(chained.trace, [
      { step: 'open', status: 'building' },
      { step: 'publish', status: 'reviewing' },
      { step: 'markReady', status: 'reviewing' },
    ]);
    assert.equal(chained.solver.calls.length, 0, 'there is nothing to fix');
    assert.deepEqual(chained.opener.ready, [{ token: TOKEN, pullRequestId: 'PR_kwDO7' }]);
    const delivered = chained.session();
    assert.equal(delivered.status, 'pr-open');
    assert.equal(delivered.failureStage, null);
    assert.equal(delivered.lastError, null);
  });

  it('holds the draft through the feedback run when the review found something', async () => {
    const chained = chain({ findings: 2 });

    const delivered = chained.deliver();
    await until(() => chained.session().status === 'fixing', 'the session to reach fixing');
    assert.deepEqual(
      chained.trace.map((step) => step.step),
      ['open', 'publish'],
      'the findings are posted and nothing is released yet',
    );
    assert.deepEqual(chained.opener.ready, [], 'the pull request is still a draft');

    chained.settle({ status: 'finished' });
    await delivered;

    assert.deepEqual(chained.trace, [
      { step: 'open', status: 'building' },
      { step: 'publish', status: 'reviewing' },
      { step: 'feedback', status: 'fixing' },
      { step: 'markReady', status: 'fixing' },
    ]);
    assert.deepEqual(chained.solver.calls, [
      { repositoryId: chained.session().repositoryId, prNumber: 7 },
    ]);
    assert.deepEqual(chained.opener.ready, [{ token: TOKEN, pullRequestId: 'PR_kwDO7' }]);
    const finished = chained.session();
    assert.equal(finished.status, 'pr-open');
    assert.equal(finished.failureStage, null);
  });

  it('undrafts and fails at the feedback stage when the run fails', async () => {
    const chained = chain({ findings: 1 });

    const delivered = chained.deliver();
    await until(() => chained.session().status === 'fixing', 'the session to reach fixing');
    chained.settle({ status: 'failed', failureStage: 'push', lastError: 'the push was rejected' });
    await delivered;

    // The fixes did not land, but the review did, so the pull request is a
    // human's to read: released first, failed second.
    assert.deepEqual(chained.trace, [
      { step: 'open', status: 'building' },
      { step: 'publish', status: 'reviewing' },
      { step: 'feedback', status: 'fixing' },
      { step: 'markReady', status: 'fixing' },
    ]);
    assert.deepEqual(chained.opener.ready, [{ token: TOKEN, pullRequestId: 'PR_kwDO7' }]);
    const failed = chained.session();
    assert.equal(failed.status, 'failed');
    assert.equal(failed.failureStage, 'feedback');
    assert.equal(isDeliveryStage(failed.failureStage), true, 'the retry re-runs the delivery');
    assert.equal(failed.prUrl, 'https://github.com/acme/demo/pull/7');
    assert.match(failed.lastError ?? '', /feedback run failed at the push/);
  });

  it('undrafts and fails at the review stage when the review is spent', async () => {
    const chained = chain({ review: reviewFailure('agent_failed', 'the agent died') });

    await chained.deliver();

    // Three attempts and no comment: nothing is coming, so the draft is not
    // left behind for a session nobody looks at again.
    assert.deepEqual(chained.trace, [
      { step: 'open', status: 'building' },
      { step: 'markReady', status: 'reviewing' },
    ]);
    assert.equal(chained.reviewer.calls, 3, 'the step spends its attempts first');
    assert.equal(chained.publisher.calls.length, 0);
    assert.equal(chained.solver.calls.length, 0);
    assert.deepEqual(chained.opener.ready, [{ token: TOKEN, pullRequestId: 'PR_kwDO7' }]);
    const failed = chained.session();
    assert.equal(failed.status, 'failed');
    assert.equal(failed.failureStage, 'review');
    assert.equal(isDeliveryStage(failed.failureStage), true);
    assert.equal(failed.prUrl, 'https://github.com/acme/demo/pull/7');
  });

  it('fails at the pull request stage when the undraft itself is refused', async () => {
    const chained = chain({ codeReview: false });
    chained.opener.readyFailure = new GithubApiError('github_forbidden', 'no write access', 403);

    await chained.deliver();

    const failed = chained.session();
    assert.equal(failed.status, 'failed');
    assert.equal(failed.failureStage, 'pull_request', 'the stage a retry re-runs the undraft from');
    assert.equal(isDeliveryStage(failed.failureStage), true);
    assert.equal(failed.prUrl, 'https://github.com/acme/demo/pull/7', 'the link survives');
    assert.match(failed.lastError ?? '', /marked ready for review/);
  });

  it('fails at the pull request stage when a reviewed pull request cannot be released', async () => {
    const chained = chain({ findings: 0 });
    chained.opener.readyFailure = new GithubApiError('github_error', 'GitHub is having a moment.');

    await chained.deliver();

    // The review went fine; only the undraft did not, so the stage names the
    // pull request rather than blaming the review for it.
    assert.deepEqual(
      chained.trace.map((step) => step.step),
      ['open', 'publish', 'markReady'],
    );
    const failed = chained.session();
    assert.equal(failed.status, 'failed');
    assert.equal(failed.failureStage, 'pull_request');
    assert.match(failed.lastError ?? '', /GitHub is having a moment\./);
  });
});

/* ------------------------------------------------- a run that changed nothing */

describe('counting what a run committed', () => {
  it('counts the feature branch over the remote base branch, with the branches in the environment', () => {
    const spec = commitCountExecSpec('main', 'chief/nightly; rm -rf /');
    assert.deepEqual(spec.cmd, ['/bin/sh', '-c', COMMIT_COUNT_SCRIPT]);
    assert.equal(spec.workingDir, CONTAINER_REPO_DIR);
    assert.deepEqual(
      [...(spec.env ?? [])],
      [
        'CHIEF_BASE_BRANCH=main',
        'CHIEF_FEATURE_BRANCH=chief/nightly; rm -rf /',
        `CHIEF_REPO_DIR=${CONTAINER_REPO_DIR}`,
      ],
    );
    assert.match(
      COMMIT_COUNT_SCRIPT,
      /git rev-list --count "origin\/\$CHIEF_BASE_BRANCH\.\.\$CHIEF_FEATURE_BRANCH"/,
    );
    assert.doesNotMatch(COMMIT_COUNT_SCRIPT, /rm -rf/);
  });

  const counted = (output: ExecOutput): Promise<CommitCount> =>
    countBranchCommits(
      { runExec: (): Promise<ExecOutput> => Promise.resolve(output) },
      'container-1',
      { baseBranch: 'main', featureBranch: 'chief/nightly', timeoutMs: 1000 },
    );

  it('reads the number git answered with', async () => {
    assert.deepEqual(await counted({ exitCode: 0, stdout: '0\n', stderr: '', timedOut: false }), {
      known: true,
      commits: 0,
      message: '',
    });
    assert.equal(
      (await counted({ exitCode: 0, stdout: '4\n', stderr: '', timedOut: false })).commits,
      4,
    );
  });

  it('never guesses: a git failure, a timeout and unreadable output are all unknown', async () => {
    for (const output of [
      { exitCode: 128, stdout: '', stderr: "fatal: bad revision 'origin/main..x'", timedOut: false },
      { exitCode: 0, stdout: '', stderr: '', timedOut: true },
      { exitCode: 0, stdout: 'lots\n', stderr: '', timedOut: false },
    ]) {
      const count = await counted(output);
      assert.equal(count.known, false, JSON.stringify(output));
      assert.equal(count.commits, 0);
    }
    assert.match(
      (
        await counted({ exitCode: 128, stdout: '', stderr: 'fatal: bad revision', timedOut: false })
      ).message,
      /git exited 128 .*fatal: bad revision/s,
    );
  });
});

describe('delivering a scheduled run that changed nothing (US-006)', () => {
  /** Runs the automatic delivery of `world`'s session and answers its opener. */
  const deliver = async (world: World): Promise<FakeOpener> => {
    const opener = new FakeOpener();
    const delivery = createDeliveryService(world.config, world.db, world.containers, world.exec, opener);
    await delivery.complete(world.session, world.stories());
    return opener;
  };

  it('skips the push, the pull request and the review, and finishes the session clean', async () => {
    const world = new World({ recurring: true });
    world.commits = { exitCode: 0, stdout: '0\n', stderr: '', timedOut: false };
    // The task asked for a code review; there is nothing to review, so the
    // step must not be reached at all.
    const reviewed = updateSession(world.db, world.session.id, { codeReview: true });
    assert.equal(reviewed?.codeReview, true);
    const opener = new FakeOpener();
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      opener,
      new ReviewStep(
        { review: (): never => assert.fail('the code review must not run for a clean run') },
        { publish: (): never => assert.fail('nothing must be published for a clean run') },
      ),
    );

    await delivery.complete(reviewed ?? world.session, world.stories());

    assert.deepEqual(
      world.execs.map((spec) => spec.cmd[2]),
      [COMMIT_COUNT_SCRIPT],
      'the count is the only thing that ran: nothing was pushed',
    );
    assert.equal(opener.calls.length, 0, 'no pull request was opened');
    assert.equal(opener.ready.length, 0, 'and nothing was undrafted');

    const finished = world.reload();
    assert.equal(finished.status, 'finished');
    assert.equal(finished.prUrl, null);
    assert.equal(finished.lastError, null);
    assert.equal(finished.failureStage, null);
  });

  it('answers the clean code and says what happened, so a retry reports it too', async () => {
    const world = new World({ recurring: true });
    world.commits = { exitCode: 0, stdout: '0\n', stderr: '', timedOut: false };
    // "Retry push & PR" on a run that is already over: the answer must be the
    // same clean one rather than a pull request GitHub would refuse.
    updateSession(world.db, world.session.id, { status: 'finished' });
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      new FakeOpener(),
    );

    const result = await delivery.retry(world.session.id);

    assert.equal(result.ok, true);
    assert.equal(result.code, 'clean');
    assert.equal(result.status, 'finished');
    assert.equal(result.prUrl, null);
    assert.match(result.message, /committed nothing on "chief\/add-login"/);
  });

  it('does not publish the branch after a story either', async () => {
    const world = new World({ recurring: true });
    world.commits = { exitCode: 0, stdout: '0\n', stderr: '', timedOut: false };
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      new FakeOpener(),
    );

    await delivery.push(world.session);

    assert.deepEqual(
      world.execs.map((spec) => spec.cmd[2]),
      [COMMIT_COUNT_SCRIPT],
    );
  });

  it('delivers a scheduled run that did commit exactly as it always has', async () => {
    const world = new World({ recurring: true });
    world.commits = { exitCode: 0, stdout: '3\n', stderr: '', timedOut: false };

    const opener = await deliver(world);

    assert.deepEqual(world.execs.map((spec) => spec.cmd[2]), [COMMIT_COUNT_SCRIPT, PUSH_SCRIPT]);
    assert.equal(opener.calls.length, 1);
    assert.equal(world.reload().status, 'pr-open');
    assert.equal(world.reload().prUrl, 'https://github.com/acme/demo/pull/7');
  });

  it('delivers as usual when git could not say how far ahead the branch is', async () => {
    const world = new World({ recurring: true });
    world.commits = { exitCode: 128, stdout: '', stderr: 'fatal: bad revision', timedOut: false };

    const opener = await deliver(world);

    assert.deepEqual(world.execs.map((spec) => spec.cmd[2]), [COMMIT_COUNT_SCRIPT, PUSH_SCRIPT]);
    assert.equal(opener.calls.length, 1, 'a count nobody could read never skips a pull request');
    assert.equal(world.reload().status, 'pr-open');
  });

  it('never asks the question of a session somebody created by hand', async () => {
    const world = new World();
    world.commits = { exitCode: 0, stdout: '0\n', stderr: '', timedOut: false };

    const opener = await deliver(world);

    assert.deepEqual(
      world.execs.map((spec) => spec.cmd[2]),
      [PUSH_SCRIPT],
      'an interactive session pushes and opens its pull request as before',
    );
    assert.equal(opener.calls.length, 1);
    assert.equal(world.reload().status, 'pr-open');
  });
});
