import assert from 'node:assert/strict';
import http from 'node:http';
import type { AddressInfo } from 'node:net';
import { after, before, describe, it } from 'node:test';

import { type Config, loadConfig } from '../config.js';
import {
  createRepository,
  createSession,
  type Database,
  getSession,
  IN_MEMORY,
  openDatabase,
  type Session,
  setSetting,
  type Story,
  syncStories,
  updateSession,
} from '../db/index.js';
import type { ExecOutput, ExecSpec } from '../docker/index.js';
import { GithubApiError, openPullRequest } from '../lib/github.js';
import type { SessionContainerView } from '../orchestrator/index.js';
import { PrFeedbackError } from '../prfeedback/index.js';
import type {
  PublishedReview,
  ReviewPassResult,
  ReviewPublisher,
  ReviewReport,
  ReviewTarget,
} from '../review/index.js';
import { CONTAINER_REPO_DIR, type SessionContainers, type SessionExecutor } from '../sessions/index.js';
import { pullRequestBody, pullRequestNumber, pullRequestTitle } from './pull-request.js';
import { PUSH_SCRIPT, pushExecSpec } from './push.js';
import { type FeedbackSolver, ReviewStep, type SessionReviewer } from './review-step.js';
import { createDeliveryService, DeliveryError, type PullRequestOpener } from './service.js';

const TOKEN = 'ghp_exampleTokenValue1234';

function story(input: Partial<Story> & Pick<Story, 'storyId' | 'priority' | 'status'>): Story {
  return {
    id: 0,
    sessionId: 's',
    title: input.storyId,
    commitSha: null,
    createdAt: '',
    updatedAt: '',
    ...input,
  };
}

describe('the push command', () => {
  it('pushes the branch by name, with an upstream and never a force', () => {
    const spec = pushExecSpec('chief/add-login');
    assert.deepEqual(spec.cmd, ['/bin/sh', '-c', PUSH_SCRIPT]);
    assert.equal(spec.workingDir, CONTAINER_REPO_DIR);
    assert.match(PUSH_SCRIPT, /git push --set-upstream origin "\$CHIEF_FEATURE_BRANCH"/);
    assert.doesNotMatch(PUSH_SCRIPT, /--force|\+refs/);
  });

  it('passes the branch in the environment, never inside the script', () => {
    const spec = pushExecSpec('chief/weird; rm -rf /');
    assert.deepEqual(
      [...(spec.env ?? [])],
      ['CHIEF_FEATURE_BRANCH=chief/weird; rm -rf /', `CHIEF_REPO_DIR=${CONTAINER_REPO_DIR}`],
    );
    assert.doesNotMatch(PUSH_SCRIPT, /rm -rf/);
  });
});

describe('the pull request body', () => {
  const session = {
    id: 'session-1',
    name: 'add-login',
    featureBranch: 'chief/add-login',
    prTargetBranch: 'develop' as const,
  };
  const stories = [
    story({ storyId: 'US-002', priority: 2, status: 'done', title: 'Second', commitSha: 'abcdef1234' }),
    story({ storyId: 'US-001', priority: 1, status: 'done', title: 'First' }),
  ];

  it('is the session name for a title', () => {
    assert.equal(pullRequestTitle({ name: 'add-login' }), 'add-login');
  });

  it('lists the completed stories by id and title, in priority order', () => {
    const body = pullRequestBody({ session, stories, publicUrl: '' });
    assert.match(body, /## Completed stories \(2\/2\)/);
    assert.ok(body.indexOf('**US-001** — First') < body.indexOf('**US-002** — Second'));
    assert.match(body, /\(`abcdef1`\)/);
  });

  it('says it was generated by chief-web, and links back when the URL is known', () => {
    assert.match(
      pullRequestBody({ session, stories, publicUrl: '' }),
      /Generated by chief-web from session `add-login`/,
    );
    assert.match(
      pullRequestBody({ session, stories, publicUrl: 'https://chief.example.com' }),
      /\[session `add-login`\]\(https:\/\/chief\.example\.com\/sessions\/session-1\)/,
    );
  });

  it('names the branches it is between, and any story left outstanding', () => {
    const body = pullRequestBody({
      session,
      stories: [...stories, story({ storyId: 'US-003', priority: 3, status: 'todo', title: 'Third' })],
      publicUrl: '',
    });
    assert.match(body, /`chief\/add-login` → `develop`/);
    assert.match(body, /## Still outstanding \(1\)/);
    assert.match(body, /\*\*US-003\*\* — Third \(todo\)/);
  });
});

/**
 * The GitHub half, against a real HTTP server speaking the REST protocol —
 * the same approach `FakeDockerDaemon` takes, so `fetch`, the headers and the
 * status mapping are all exercised for real.
 */
describe('opening a pull request', () => {
  let baseUrl: string;
  let server: http.Server;
  /** What the stub answers, keyed by `<method> <pathname>`. */
  let replies: Record<string, { status: number; body: unknown }> = {};
  let requests: { method: string; url: string; body: unknown; auth?: string | undefined }[] = [];

  before(async () => {
    server = http.createServer((req, res) => {
      const chunks: Buffer[] = [];
      req.on('data', (chunk: Buffer) => chunks.push(chunk));
      req.on('end', () => {
        const raw = Buffer.concat(chunks).toString('utf8');
        const url = new URL(req.url ?? '/', 'http://localhost');
        requests.push({
          method: req.method ?? '',
          url: req.url ?? '',
          body: raw === '' ? null : (JSON.parse(raw) as unknown),
          auth: req.headers.authorization,
        });
        const reply = replies[`${req.method ?? ''} ${url.pathname}`] ?? {
          status: 404,
          body: { message: 'Not Found' },
        };
        res.writeHead(reply.status, { 'content-type': 'application/json' });
        res.end(JSON.stringify(reply.body));
      });
    });
    server.listen(0, '127.0.0.1');
    await new Promise((resolve) => server.once('listening', resolve));
    baseUrl = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  });

  after(async () => {
    await new Promise((resolve) => server.close(resolve));
  });

  const input = {
    slug: 'acme/demo',
    head: 'chief/add-login',
    base: 'develop',
    title: 'add-login',
    body: 'Generated by chief-web.',
  };

  it('creates one when there is none, with the title, body, head and base', async () => {
    replies = {
      'GET /repos/acme/demo/pulls': { status: 200, body: [] },
      'POST /repos/acme/demo/pulls': {
        status: 201,
        body: { number: 7, html_url: 'https://github.com/acme/demo/pull/7', state: 'open' },
      },
    };
    requests = [];

    const opened = await openPullRequest(TOKEN, baseUrl, input);
    assert.deepEqual(opened, {
      pullRequest: { number: 7, url: 'https://github.com/acme/demo/pull/7', state: 'open' },
      adopted: false,
    });

    const [lookup, created] = requests;
    // The head of a same-repository branch is still qualified `owner:branch`.
    assert.match(lookup?.url ?? '', /head=acme%3Achief%2Fadd-login/);
    assert.match(lookup?.url ?? '', /base=develop/);
    assert.equal(created?.auth, `Bearer ${TOKEN}`);
    assert.deepEqual(created?.body, {
      title: 'add-login',
      body: 'Generated by chief-web.',
      head: 'chief/add-login',
      base: 'develop',
    });
  });

  it('adopts the existing one instead of creating a duplicate', async () => {
    replies = {
      'GET /repos/acme/demo/pulls': {
        status: 200,
        body: [{ number: 4, html_url: 'https://github.com/acme/demo/pull/4', state: 'open' }],
      },
    };
    requests = [];

    const opened = await openPullRequest(TOKEN, baseUrl, input);
    assert.equal(opened.adopted, true);
    assert.equal(opened.pullRequest.url, 'https://github.com/acme/demo/pull/4');
    // Nothing was posted: the lookup is the only call.
    assert.deepEqual(requests.map((request) => request.method), ['GET']);
  });

  it('adopts the one a race created, when GitHub answers 422', async () => {
    let lookups = 0;
    replies = {
      'POST /repos/acme/demo/pulls': {
        status: 422,
        body: {
          message: 'Validation Failed',
          errors: [{ message: 'A pull request already exists for acme:chief/add-login.' }],
        },
      },
    };
    // The first lookup finds nothing, the one after the 422 finds the race's.
    server.removeAllListeners('request');
    server.on('request', (req, res) => {
      req.resume();
      const url = new URL(req.url ?? '/', 'http://localhost');
      if (req.method === 'GET') {
        lookups += 1;
        res.writeHead(200, { 'content-type': 'application/json' });
        res.end(
          JSON.stringify(
            lookups === 1
              ? []
              : [{ number: 9, html_url: 'https://github.com/acme/demo/pull/9', state: 'open' }],
          ),
        );
        return;
      }
      const reply = replies[`POST ${url.pathname}`] ?? { status: 500, body: {} };
      res.writeHead(reply.status, { 'content-type': 'application/json' });
      res.end(JSON.stringify(reply.body));
    });

    const opened = await openPullRequest(TOKEN, baseUrl, input);
    assert.equal(opened.adopted, true);
    assert.equal(opened.pullRequest.number, 9);
    assert.equal(lookups, 2);
  });

  it('reports what GitHub said when it refuses for another reason', async () => {
    server.removeAllListeners('request');
    server.on('request', (req, res) => {
      req.resume();
      if (req.method === 'GET') {
        res.writeHead(200, { 'content-type': 'application/json' });
        res.end('[]');
        return;
      }
      res.writeHead(422, { 'content-type': 'application/json' });
      res.end(
        JSON.stringify({
          message: 'Validation Failed',
          errors: [{ message: 'No commits between develop and chief/add-login' }],
        }),
      );
    });

    const failure = await openPullRequest(TOKEN, baseUrl, input).catch((cause: unknown) => cause);
    assert.ok(failure instanceof GithubApiError);
    assert.equal(failure.code, 'github_rejected');
    assert.match(failure.message, /No commits between develop and chief\/add-login/);
  });
});

/** A session container that answers whatever the test scripts. */
class World {
  readonly config: Config;
  readonly db: Database;
  readonly session: Session;
  readonly containers: SessionContainers;
  readonly execs: ExecSpec[] = [];
  /** What the push exec answers with. */
  push: ExecOutput = { exitCode: 0, stdout: '', stderr: 'Branch set up to track origin.', timedOut: false };
  containerFailure: Error | null = null;

  constructor(options: { slug?: string; publicUrl?: string } = {}) {
    this.config = loadConfig(
      options.publicUrl === undefined ? {} : { PUBLIC_URL: options.publicUrl },
    );
    this.db = openDatabase(IN_MEMORY);
    const repository = createRepository(this.db, {
      name: 'demo',
      sshUrl: 'git@github.com:acme/demo.git',
      githubSlug: options.slug ?? 'acme/demo',
    });
    this.session =
      updateSession(
        this.db,
        createSession(this.db, {
          repositoryId: repository.id,
          name: 'add-login',
          baseBranch: 'main',
          prTargetBranch: 'develop',
        }).id,
        { status: 'building' },
      ) ?? (undefined as never);
    setSetting(this.db, 'github_token', TOKEN);
    syncStories(this.db, this.session.id, [
      { storyId: 'US-001', title: 'First', priority: 1, status: 'done' },
      { storyId: 'US-002', title: 'Second', priority: 2, status: 'done' },
    ]);

    this.containers = {
      start: (): Promise<SessionContainerView> =>
        this.containerFailure === null
          ? Promise.resolve({
              id: 'container-1',
              name: 'chief-web-add-login',
              running: true,
              state: 'running',
            })
          : Promise.reject(this.containerFailure),
      remove: (): Promise<void> => Promise.resolve(),
    };
  }

  get exec(): SessionExecutor {
    return {
      runExec: (_container: string, spec: ExecSpec): Promise<ExecOutput> => {
        this.execs.push(spec);
        return Promise.resolve(this.push);
      },
    };
  }

  reload(): Session {
    return getSession(this.db, this.session.id) ?? (undefined as never);
  }

  stories(): Story[] {
    return [
      story({ storyId: 'US-001', priority: 1, status: 'done' }),
      story({ storyId: 'US-002', priority: 2, status: 'done' }),
    ];
  }
}

/** A {@link PullRequestOpener} the test scripts. */
class FakeOpener implements PullRequestOpener {
  readonly calls: { token: string; input: Parameters<PullRequestOpener['open']>[1] }[] = [];
  adopted = false;
  failure: Error | null = null;
  url = 'https://github.com/acme/demo/pull/7';

  open(
    token: string,
    input: Parameters<PullRequestOpener['open']>[1],
  ): ReturnType<PullRequestOpener['open']> {
    this.calls.push({ token, input });
    if (this.failure !== null) return Promise.reject(this.failure);
    return Promise.resolve({
      pullRequest: { number: 7, url: this.url, state: 'open' },
      adopted: this.adopted,
    });
  }
}

describe('delivering a finished session', () => {
  it('pushes, opens the pull request, and leaves the session pr-open', async () => {
    const world = new World({ publicUrl: 'https://chief.example.com/' });
    const opener = new FakeOpener();
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      opener,
    );

    await delivery.complete(world.session, world.stories());

    assert.equal(world.execs.length, 1);
    assert.deepEqual(world.execs[0]?.cmd, ['/bin/sh', '-c', PUSH_SCRIPT]);

    const call = opener.calls[0];
    assert.equal(call?.token, TOKEN);
    assert.equal(call?.input.slug, 'acme/demo');
    assert.equal(call?.input.head, 'chief/add-login');
    assert.equal(call?.input.base, 'develop');
    assert.equal(call?.input.title, 'add-login');
    assert.match(call?.input.body ?? '', /\*\*US-001\*\* — US-001/);
    assert.match(call?.input.body ?? '', /https:\/\/chief\.example\.com\/sessions\//);

    // The pull request is open, so the session is `pr-open` and not `finished`
    // (US-002); only the sync moves it on from there.
    const delivered = world.reload();
    assert.equal(delivered.status, 'pr-open');
    assert.equal(delivered.prUrl, 'https://github.com/acme/demo/pull/7');
    assert.equal(delivered.lastError, null);
  });

  it('adopts an existing pull request without failing', async () => {
    const world = new World();
    const opener = new FakeOpener();
    opener.adopted = true;
    opener.url = 'https://github.com/acme/demo/pull/4';
    const delivery = createDeliveryService(world.config, world.db, world.containers, world.exec, opener);

    const result = await delivery.retry(world.session.id).catch(() => null);
    // A building session cannot be retried; deliver through the loop's seam.
    assert.equal(result, null);

    await delivery.complete(world.session, world.stories());
    assert.equal(world.reload().prUrl, 'https://github.com/acme/demo/pull/4');
    assert.equal(world.reload().status, 'pr-open');
  });

  it('fails the session with git stderr when the push is rejected', async () => {
    const world = new World();
    world.push = {
      exitCode: 1,
      stdout: '',
      stderr: '! [rejected] chief/add-login -> chief/add-login (fetch first)',
      timedOut: false,
    };
    const opener = new FakeOpener();
    const delivery = createDeliveryService(world.config, world.db, world.containers, world.exec, opener);

    await delivery.complete(world.session, world.stories());

    const failed = world.reload();
    assert.equal(failed.status, 'failed');
    assert.match(failed.lastError ?? '', /Pushing "chief\/add-login" to origin failed/);
    assert.match(failed.lastError ?? '', /\[rejected\]/);
    assert.equal(opener.calls.length, 0, 'no pull request is attempted after a failed push');
  });

  it('fails the session with GitHub’s own message when the pull request is refused', async () => {
    const world = new World();
    const opener = new FakeOpener();
    opener.failure = new GithubApiError(
      'github_rejected',
      'GitHub rejected the request: No commits between develop and chief/add-login',
      422,
    );
    const delivery = createDeliveryService(world.config, world.db, world.containers, world.exec, opener);

    await delivery.complete(world.session, world.stories());

    const failed = world.reload();
    assert.equal(failed.status, 'failed');
    assert.match(failed.lastError ?? '', /No commits between develop and chief\/add-login/);
  });

  it('fails when there is no token, and says the branch was pushed anyway', async () => {
    const world = new World();
    setSetting(world.db, 'github_token', '');
    world.db.prepare("DELETE FROM settings WHERE key = 'github_token'").run();
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      new FakeOpener(),
    );

    await delivery.complete(world.session, world.stories());
    const failed = world.reload();
    assert.equal(failed.status, 'failed');
    assert.match(failed.lastError ?? '', /branch was pushed, but no GitHub token is configured/);
  });

  it('refuses a repository whose slug is not owner/repo', async () => {
    const world = new World({ slug: 'not a slug' });
    const opener = new FakeOpener();
    const delivery = createDeliveryService(world.config, world.db, world.containers, world.exec, opener);

    await delivery.complete(world.session, world.stories());
    assert.equal(opener.calls.length, 0);
    assert.match(world.reload().lastError ?? '', /is not a GitHub owner\/repo slug/);
  });

  it('fails with the reason when the session container cannot be started', async () => {
    const world = new World();
    world.containerFailure = new Error('Cannot connect to the Docker daemon');
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      new FakeOpener(),
    );

    await delivery.complete(world.session, world.stories());
    assert.match(world.reload().lastError ?? '', /Cannot connect to the Docker daemon/);
    assert.equal(world.reload().status, 'failed');
  });
});

describe('pushing after each completed story', () => {
  it('pushes without touching the session, so the build is never ended by it', async () => {
    const world = new World();
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      new FakeOpener(),
    );

    await delivery.push(world.session);
    assert.equal(world.execs.length, 1);
    assert.equal(world.reload().status, 'building');
  });

  it('swallows a failed push: the commits are safe locally', async () => {
    const world = new World();
    world.push = { exitCode: 128, stdout: '', stderr: 'fatal: could not read from remote', timedOut: false };
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      new FakeOpener(),
    );

    await delivery.push(world.session);
    const unchanged = world.reload();
    assert.equal(unchanged.status, 'building');
    assert.equal(unchanged.lastError, null);
  });

  it('swallows an unreachable daemon too', async () => {
    const world = new World();
    world.containerFailure = new Error('no daemon');
    const delivery = createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      new FakeOpener(),
    );

    await delivery.push(world.session);
    assert.equal(world.reload().status, 'building');
  });
});

describe('retrying a delivery', () => {
  function serviceFor(world: World, opener: PullRequestOpener) {
    return createDeliveryService(world.config, world.db, world.containers, world.exec, opener);
  }

  it('re-attempts only the push and the pull request', async () => {
    const world = new World();
    updateSession(world.db, world.session.id, { status: 'failed', lastError: 'push failed' });
    const opener = new FakeOpener();

    const result = await serviceFor(world, opener).retry(world.session.id);

    assert.equal(result.ok, true);
    assert.equal(result.prUrl, 'https://github.com/acme/demo/pull/7');
    assert.equal(world.execs.length, 1, 'exactly one command ran: the push');
    assert.equal(opener.calls.length, 1);
    assert.equal(world.reload().status, 'pr-open');
    assert.equal(world.reload().lastError, null);
  });

  it('ends a retried pull_request failure in pr-open, not finished', async () => {
    const world = new World();
    const opener = new FakeOpener();
    opener.failure = new GithubApiError('github_rejected', 'GitHub is having a moment', 500);
    const delivery = serviceFor(world, opener);

    await delivery.complete(world.session, world.stories());
    const failed = world.reload();
    assert.equal(failed.status, 'failed');
    assert.equal(failed.failureStage, 'pull_request');

    // The same session, retried once GitHub answers: the delivery that opens
    // the pull request lands in `pr-open` whether it is the first attempt or
    // the fifth.
    opener.failure = null;
    const result = await delivery.retry(world.session.id);

    assert.equal(result.ok, true);
    assert.equal(result.status, 'pr-open');
    const delivered = world.reload();
    assert.equal(delivered.status, 'pr-open');
    assert.equal(delivered.prUrl, 'https://github.com/acme/demo/pull/7');
    assert.equal(delivered.failureStage, null);
    assert.equal(delivered.lastError, null);
  });

  it('reports a failure as an answer, not as a failed request', async () => {
    const world = new World();
    updateSession(world.db, world.session.id, { status: 'failed' });
    world.push = { exitCode: 1, stdout: '', stderr: 'Permission denied (publickey).', timedOut: false };

    const result = await serviceFor(world, new FakeOpener()).retry(world.session.id);
    assert.equal(result.ok, false);
    assert.equal(result.code, 'push_failed');
    assert.match(result.stderr, /Permission denied/);
    assert.equal(world.reload().status, 'failed');
  });

  it('refuses while the session is still building', async () => {
    const world = new World();
    const failure = await serviceFor(world, new FakeOpener())
      .retry(world.session.id)
      .catch((cause: unknown) => cause);
    assert.ok(failure instanceof DeliveryError);
    assert.equal(failure.status, 409);
    assert.equal(failure.code, 'session_is_building');
  });

  it('refuses while a story is still outstanding', async () => {
    const world = new World();
    updateSession(world.db, world.session.id, { status: 'failed' });
    syncStories(world.db, world.session.id, [
      { storyId: 'US-001', title: 'First', priority: 1, status: 'done' },
      { storyId: 'US-002', title: 'Second', priority: 2, status: 'todo' },
    ]);

    const failure = await serviceFor(world, new FakeOpener())
      .retry(world.session.id)
      .catch((cause: unknown) => cause);
    assert.ok(failure instanceof DeliveryError);
    assert.equal(failure.code, 'session_not_complete');
    assert.match(failure.message, /1 of 2 stories/);
  });

  it('is 404 for a session that no longer exists', async () => {
    const world = new World();
    const failure = await serviceFor(world, new FakeOpener())
      .retry('nope')
      .catch((cause: unknown) => cause);
    assert.ok(failure instanceof DeliveryError);
    assert.equal(failure.status, 404);
  });
});

/** A review pass the test scripts, one outcome per attempt. */
class FakeReviewer implements SessionReviewer {
  calls = 0;
  /** Consumed one per attempt; the last one repeats for every attempt after. */
  outcomes: ReviewPassResult[] = [reviewPass()];

  review(session: Session): Promise<ReviewPassResult> {
    this.calls += 1;
    const outcome =
      this.outcomes[Math.min(this.calls - 1, this.outcomes.length - 1)] ?? reviewPass();
    return Promise.resolve({ ...outcome, sessionId: session.id });
  }
}

/** A {@link ReviewPublisher} the test scripts the same way. */
class FakePublisher implements ReviewPublisher {
  readonly calls: { token: string; target: ReviewTarget; report: ReviewReport }[] = [];
  /** Consumed one per call; the last one repeats. `null` is a success. */
  failures: (Error | null)[] = [null];

  publish(token: string, target: ReviewTarget, report: ReviewReport): Promise<PublishedReview> {
    this.calls.push({ token, target, report });
    const failure = this.failures[Math.min(this.calls.length - 1, this.failures.length - 1)] ?? null;
    if (failure !== null) return Promise.reject(failure);
    return Promise.resolve({
      url: 'https://github.com/acme/demo/pull/7#pullrequestreview-1',
      inlineComments: report.findings.length,
      foldedFindings: 0,
    });
  }
}

function reviewPass(findings = 1): ReviewPassResult {
  return {
    ok: true,
    sessionId: 's',
    code: 'ok',
    message: 'The review found something to comment on.',
    report: {
      summary: 'Two files changed; one thing worth a look.',
      findings: Array.from({ length: findings }, (_unused, index) => ({
        path: 'src/index.ts',
        line: index + 1,
        body: 'This can be null here.',
      })),
    },
    output: '',
  };
}

function reviewFailure(code: ReviewPassResult['code'], message: string): ReviewPassResult {
  return { ok: false, sessionId: 's', code, message, report: null, output: '' };
}

describe('the code review of a delivery', () => {
  function serviceFor(world: World, opener: PullRequestOpener, step: ReviewStep) {
    return createDeliveryService(world.config, world.db, world.containers, world.exec, opener, step);
  }

  /** The session as the build loop hands it over, with the flag on. */
  function reviewedSession(world: World): Session {
    return updateSession(world.db, world.session.id, { codeReview: true }) ?? (undefined as never);
  }

  it('does not review a session with the flag off', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    const publisher = new FakePublisher();
    const delivery = serviceFor(world, new FakeOpener(), new ReviewStep(reviewer, publisher));

    await delivery.complete(world.session, world.stories());

    assert.equal(reviewer.calls, 0, 'no review is run for a session that did not ask for one');
    assert.equal(publisher.calls.length, 0);
    const finished = world.reload();
    assert.equal(finished.status, 'pr-open');
    assert.equal(finished.prUrl, 'https://github.com/acme/demo/pull/7');
    assert.equal(finished.lastError, null);
  });

  it('reviews the pull request it just opened, then finishes the session', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    const publisher = new FakePublisher();
    const delivery = serviceFor(world, new FakeOpener(), new ReviewStep(reviewer, publisher));

    const result = await delivery.retry(reviewedSession(world).id).catch(() => null);
    assert.equal(result, null, 'a building session is delivered through the loop’s seam');
    await delivery.complete(reviewedSession(world), world.stories());

    assert.equal(reviewer.calls, 1);
    assert.equal(publisher.calls.length, 1);
    assert.equal(publisher.calls[0]?.token, TOKEN);
    assert.deepEqual(publisher.calls[0]?.target, { slug: 'acme/demo', number: 7 });
    const finished = world.reload();
    assert.equal(finished.status, 'pr-open');
    assert.equal(finished.prUrl, 'https://github.com/acme/demo/pull/7');
    assert.equal(finished.lastError, null);
  });

  it('retries a failed attempt and finishes on the second', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [
      reviewFailure('agent_timed_out', 'The review agent ran out of time.'),
      reviewPass(),
    ];
    const publisher = new FakePublisher();
    const opener = new FakeOpener();
    const delivery = serviceFor(world, opener, new ReviewStep(reviewer, publisher));

    await delivery.complete(reviewedSession(world), world.stories());

    assert.equal(reviewer.calls, 2);
    assert.equal(publisher.calls.length, 1, 'only the attempt that produced findings posted');
    assert.equal(world.reload().status, 'pr-open');
    assert.equal(world.reload().lastError, null);
    // The half of the delivery that already worked is not repeated by a retry.
    assert.equal(world.execs.length, 1, 'exactly one push');
    assert.equal(opener.calls.length, 1, 'exactly one pull request');
  });

  it('retries a GitHub posting error too', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    const publisher = new FakePublisher();
    publisher.failures = [new GithubApiError('github_unreachable', 'GitHub is unreachable.', 0), null];
    const delivery = serviceFor(world, new FakeOpener(), new ReviewStep(reviewer, publisher));

    await delivery.complete(reviewedSession(world), world.stories());

    assert.equal(reviewer.calls, 2, 'a posting failure costs a whole attempt, review included');
    assert.equal(publisher.calls.length, 2);
    assert.equal(world.reload().status, 'pr-open');
  });

  it('fails the session at the review stage after three attempts, keeping the pull request', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewFailure('invalid_findings', 'The findings could not be read.')];
    const publisher = new FakePublisher();
    const opener = new FakeOpener();
    const delivery = serviceFor(world, opener, new ReviewStep(reviewer, publisher));

    const result = await delivery.complete(reviewedSession(world), world.stories());
    assert.equal(result, undefined, 'the loop’s hand-off answers nothing');

    assert.equal(reviewer.calls, 3, 'three attempts, then no more');
    assert.equal(publisher.calls.length, 0);
    const failed = world.reload();
    assert.equal(failed.status, 'failed');
    assert.equal(failed.failureStage, 'review');
    assert.match(failed.lastError ?? '', /failed after 3 attempts/);
    assert.match(failed.lastError ?? '', /The findings could not be read\./);
    assert.equal(failed.prUrl, 'https://github.com/acme/demo/pull/7', 'the pull request is kept');
    assert.equal(world.execs.length, 1, 'the push was not repeated');
    assert.equal(opener.calls.length, 1, 'the pull request was not opened again');
  });

  it('stops at the first attempt when the account is out of usage', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewFailure('usage_limit', 'The review agent stopped on a usage limit.')];
    const delivery = serviceFor(world, new FakeOpener(), new ReviewStep(reviewer, new FakePublisher()));

    await delivery.complete(reviewedSession(world), world.stories());

    assert.equal(reviewer.calls, 1, 'a second attempt walks into the same wall');
    assert.equal(world.reload().failureStage, 'review');
    assert.match(world.reload().lastError ?? '', /usage limit/);
  });

  it('finishes a review that found nothing exactly like one that did', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewPass(0)];
    const publisher = new FakePublisher();
    const delivery = serviceFor(world, new FakeOpener(), new ReviewStep(reviewer, publisher));

    await delivery.complete(reviewedSession(world), world.stories());

    assert.equal(publisher.calls.length, 1);
    assert.deepEqual(publisher.calls[0]?.report.findings, []);
    const finished = world.reload();
    assert.equal(finished.status, 'pr-open');
    assert.equal(finished.failureStage, null);
    assert.equal(finished.lastError, null);
  });
});

/** The PR-feedback solver, scripted: it starts a run or refuses like the real one. */
class FakeSolver implements FeedbackSolver {
  readonly calls: { repositoryId: string; prNumber: number }[] = [];
  /** What `start` rejects with; `null` starts a run. */
  refusal: Error | null = null;

  start(repositoryId: string, prNumber: number): Promise<{ id: string }> {
    this.calls.push({ repositoryId, prNumber });
    if (this.refusal !== null) return Promise.reject(this.refusal);
    return Promise.resolve({ id: 'run-1' });
  }
}

describe('chaining into the pull request feedback solver', () => {
  function serviceFor(world: World, step: ReviewStep) {
    return createDeliveryService(
      world.config,
      world.db,
      world.containers,
      world.exec,
      new FakeOpener(),
      step,
    );
  }

  /** The session as the build loop hands it over, with the flag on. */
  function reviewedSession(world: World): Session {
    return updateSession(world.db, world.session.id, { codeReview: true }) ?? (undefined as never);
  }

  it('starts a run on the reviewed pull request once the findings are posted', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewPass(2)];
    const solver = new FakeSolver();
    const delivery = serviceFor(
      world,
      new ReviewStep(reviewer, new FakePublisher(), () => solver),
    );

    const result = await delivery.retry(reviewedSession(world).id).catch(() => null);
    assert.equal(result, null, 'a building session is delivered through the loop’s seam');
    await delivery.complete(reviewedSession(world), world.stories());

    assert.deepEqual(solver.calls, [{ repositoryId: world.session.repositoryId, prNumber: 7 }]);
    const finished = world.reload();
    assert.equal(finished.status, 'pr-open');
    assert.equal(finished.lastError, null);
  });

  it('does not start a run when the review found nothing to solve', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewPass(0)];
    const solver = new FakeSolver();

    await serviceFor(world, new ReviewStep(reviewer, new FakePublisher(), () => solver)).complete(
      reviewedSession(world),
      world.stories(),
    );

    assert.equal(solver.calls.length, 0, 'there is nothing on the pull request to work on');
    assert.equal(world.reload().status, 'pr-open');
  });

  it('finishes the session anyway when the solver refuses the run', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    const solver = new FakeSolver();
    solver.refusal = new PrFeedbackError(
      409,
      'no_free_slot',
      'Every build slot is in use. Wait for one to free, or raise the cap on the settings page.',
    );

    const result = await serviceFor(
      world,
      new ReviewStep(reviewer, new FakePublisher(), () => solver),
    ).complete(reviewedSession(world), world.stories());

    assert.equal(result, undefined, 'the loop’s hand-off answers nothing either way');
    assert.equal(solver.calls.length, 1);
    const finished = world.reload();
    assert.equal(finished.status, 'pr-open', 'a refused run is not the session’s problem');
    assert.equal(finished.failureStage, null);
    assert.equal(finished.lastError, null);
  });

  it('reports the refusal the way the PullRequests page would', async () => {
    const world = new World();
    failedAtReviewFor(world);
    const solver = new FakeSolver();
    solver.refusal = new PrFeedbackError(409, 'no_free_slot', 'Every build slot is in use.');

    const result = await serviceFor(
      world,
      new ReviewStep(new FakeReviewer(), new FakePublisher(), () => solver),
    ).retry(world.session.id);

    assert.equal(result.ok, true);
    assert.match(result.message, /Every build slot is in use\./);
  });

  it('starts nothing when the review never posted', async () => {
    const world = new World();
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewFailure('invalid_findings', 'The findings could not be read.')];
    const solver = new FakeSolver();

    await serviceFor(world, new ReviewStep(reviewer, new FakePublisher(), () => solver)).complete(
      reviewedSession(world),
      world.stories(),
    );

    assert.equal(solver.calls.length, 0, 'there are no findings on the pull request');
    assert.equal(world.reload().failureStage, 'review');
  });
});

/** A session parked exactly where a review retry picks it up. */
function failedAtReviewFor(world: World): void {
  updateSession(world.db, world.session.id, {
    status: 'failed',
    failureStage: 'review',
    lastError: 'The code review failed after 3 attempts.',
    prUrl: 'https://github.com/acme/demo/pull/7',
    codeReview: true,
  });
}

describe('retrying a session that failed at the review', () => {
  function failedAtReview(world: World, codeReview = true): void {
    updateSession(world.db, world.session.id, {
      status: 'failed',
      failureStage: 'review',
      lastError: 'The code review failed after 3 attempts.',
      prUrl: 'https://github.com/acme/demo/pull/7',
      codeReview,
    });
  }

  function serviceFor(world: World, opener: PullRequestOpener, step: ReviewStep) {
    return createDeliveryService(world.config, world.db, world.containers, world.exec, opener, step);
  }

  it('re-runs the review only, and finishes the session', async () => {
    const world = new World();
    failedAtReview(world);
    const reviewer = new FakeReviewer();
    const publisher = new FakePublisher();
    const opener = new FakeOpener();

    const result = await serviceFor(world, opener, new ReviewStep(reviewer, publisher)).retry(
      world.session.id,
    );

    assert.equal(result.ok, true);
    assert.equal(result.prUrl, 'https://github.com/acme/demo/pull/7');
    assert.equal(world.execs.length, 0, 'nothing was pushed again');
    assert.equal(opener.calls.length, 0, 'the pull request was not opened again');
    assert.equal(reviewer.calls, 1);
    assert.deepEqual(publisher.calls[0]?.target, { slug: 'acme/demo', number: 7 });
    const finished = world.reload();
    assert.equal(finished.status, 'pr-open');
    assert.equal(finished.failureStage, null);
    assert.equal(finished.lastError, null);
  });

  it('gives the retry its own three attempts before failing again', async () => {
    const world = new World();
    failedAtReview(world);
    const reviewer = new FakeReviewer();
    reviewer.outcomes = [reviewFailure('agent_failed', 'The review agent exited with code 1.')];
    const opener = new FakeOpener();

    const result = await serviceFor(world, opener, new ReviewStep(reviewer, new FakePublisher())).retry(
      world.session.id,
    );

    assert.equal(result.ok, false);
    assert.equal(result.code, 'review_failed');
    assert.equal(reviewer.calls, 3);
    assert.equal(world.execs.length, 0);
    assert.equal(opener.calls.length, 0);
    const failed = world.reload();
    assert.equal(failed.status, 'failed');
    assert.equal(failed.failureStage, 'review');
    assert.equal(failed.prUrl, 'https://github.com/acme/demo/pull/7');
  });

  it('just finishes the session when the review was switched off since', async () => {
    const world = new World();
    failedAtReview(world, false);
    const reviewer = new FakeReviewer();

    const result = await serviceFor(world, new FakeOpener(), new ReviewStep(reviewer, new FakePublisher()))
      .retry(world.session.id);

    assert.equal(result.ok, true);
    assert.equal(reviewer.calls, 0);
    assert.equal(world.reload().status, 'pr-open');
  });

  it('delivers in full when the failed session has no pull request URL', async () => {
    const world = new World();
    failedAtReview(world);
    updateSession(world.db, world.session.id, { prUrl: null });
    const opener = new FakeOpener();
    const reviewer = new FakeReviewer();

    await serviceFor(world, opener, new ReviewStep(reviewer, new FakePublisher())).retry(
      world.session.id,
    );

    assert.equal(world.execs.length, 1, 'without a pull request there is one to open again');
    assert.equal(opener.calls.length, 1);
    assert.equal(reviewer.calls, 1);
    assert.equal(world.reload().status, 'pr-open');
  });
});

describe('the pull request number in a URL', () => {
  it('reads the number a session stores its pull request as', () => {
    assert.equal(pullRequestNumber('https://github.com/acme/demo/pull/7'), 7);
    assert.equal(pullRequestNumber('https://github.com/acme/demo/pull/1234#issuecomment-1'), 1234);
    assert.equal(pullRequestNumber('https://github.example.com/acme/demo/pull/9/files'), 9);
  });

  it('answers null rather than guessing at anything else', () => {
    assert.equal(pullRequestNumber(null), null);
    assert.equal(pullRequestNumber(''), null);
    assert.equal(pullRequestNumber('https://github.com/acme/demo/pulls'), null);
    assert.equal(pullRequestNumber('https://github.com/acme/demo/pull/abc'), null);
    assert.equal(pullRequestNumber('https://github.com/acme/demo/pull/0'), null);
  });
});
