import type { Session, Story } from '../db/index.js';

/**
 * What the generated pull request says (US-014).
 *
 * The title is the session name — that is the name the operator gave the piece
 * of work, and it is what the sessions list shows — and the body is the list of
 * stories the loop actually finished, so a reviewer can see what is in the
 * branch without reading the PRD.
 */

/** The pull request's title: the session name, nothing else. */
export function pullRequestTitle(session: Pick<Session, 'name'>): string {
  return session.name;
}

export interface PullRequestBodyInput {
  readonly session: Pick<Session, 'id' | 'name' | 'featureBranch' | 'prTargetBranch'>;
  readonly stories: readonly Story[];
  /** Base URL of this chief-web, for the link back; empty when unknown. */
  readonly publicUrl: string;
}

/**
 * The body: the completed stories with their ids and titles, and a note saying
 * where the branch came from. When chief-web knows its own URL that note links
 * back to the session page; otherwise it just names the session, because a
 * fabricated link is worse than none.
 */
export function pullRequestBody(input: PullRequestBodyInput): string {
  const { session, stories, publicUrl } = input;
  const done = stories.filter((story) => story.status === 'done');
  const outstanding = stories.filter((story) => story.status !== 'done');

  const lines: string[] = [
    `Autonomous build of session **${session.name}**, ` +
      `\`${session.featureBranch}\` → \`${session.prTargetBranch}\`.`,
    '',
    `## Completed stories (${String(done.length)}/${String(stories.length)})`,
    '',
  ];

  if (done.length === 0) {
    lines.push('_No story was completed on this branch._');
  } else {
    for (const story of sorted(done)) {
      lines.push(`- **${story.storyId}** — ${story.title}${commitOf(story)}`);
    }
  }

  if (outstanding.length > 0) {
    lines.push('', `## Still outstanding (${String(outstanding.length)})`, '');
    for (const story of sorted(outstanding)) {
      lines.push(`- **${story.storyId}** — ${story.title} (${story.status})`);
    }
  }

  lines.push('', '---', '', generatedBy(session, publicUrl));
  return `${lines.join('\n')}\n`;
}

/** Priority order, exactly the order the build loop worked through them in. */
function sorted(stories: readonly Story[]): Story[] {
  return [...stories].sort(
    (left, right) =>
      left.priority - right.priority || left.storyId.localeCompare(right.storyId),
  );
}

function commitOf(story: Story): string {
  return story.commitSha === null ? '' : ` (\`${story.commitSha.slice(0, 7)}\`)`;
}

function generatedBy(
  session: Pick<Session, 'id' | 'name'>,
  publicUrl: string,
): string {
  const link =
    publicUrl === ''
      ? `session \`${session.name}\``
      : `[session \`${session.name}\`](${publicUrl}/sessions/${encodeURIComponent(session.id)})`;
  return `🤖 Generated by chief-web from ${link}.`;
}
