import type { RecurringTask } from '../db/index.js';

/**
 * The PRD a recurring-task run is given (US-004).
 *
 * A run has no planning step: nobody writes its PRD, so chief-web writes one
 * for it — a fixed template with exactly one story, built around the prompt the
 * task stores. From there the session is an ordinary one: the same parser reads
 * this file, the same build loop runs its story, and the same delivery opens
 * the pull request.
 *
 * Two properties make that safe, and both are about the prompt being *data*:
 *
 *   - it is quoted line by line, so a prompt that itself contains `### US-002`
 *     headings, `- [ ]` checkboxes or `**Status:**` lines cannot add stories,
 *     criteria or a status to this document — the parser reads `> ` first and
 *     sees prose;
 *   - the criteria say in as many words that changing nothing is a valid
 *     outcome, because a story the agent cannot honestly finish is a story it
 *     will finish dishonestly, and an empty commit on a nightly job is worse
 *     than no run at all.
 *
 * The prompt appears twice, on purpose. What actually reaches the agent is the
 * story's `**Description:**`, because the build loop hands it the story as JSON
 * and nothing else of the file — and a description is one line, so the prompt
 * is flattened into it. The quoted block under it is the original, kept line for
 * line for whoever opens the PRD, agent or human.
 */

/** The one story every generated PRD has. */
export const GENERATED_STORY_ID = 'US-001';

/**
 * `YYYYMMDD-HHmm` in UTC.
 *
 * Cron is read in the server’s timezone, so the obvious thing would be to stamp
 * the run with the same local clock the schedule was written in. UTC instead,
 * because a name has one job the local clock cannot do: be unique. Local wall
 * time repeats an hour every autumn, so a sub-daily task fires twice at the
 * same `YYYYMMDD-HHmm`, and the second of those runs is refused the session
 * name the first one took — one occurrence lost to the clock, once a year, on
 * every deployment that is not already running in UTC.
 */
export function runTimestamp(at: Date): string {
  const pad = (value: number): string => String(value).padStart(2, '0');
  return (
    `${String(at.getUTCFullYear())}${pad(at.getUTCMonth() + 1)}${pad(at.getUTCDate())}` +
    `-${pad(at.getUTCHours())}${pad(at.getUTCMinutes())}`
  );
}

/**
 * `<task-name>-<YYYYMMDD-HHmm>` in UTC: the name of one run, and the reason a
 * task name is capped at `MAX_RECURRING_TASK_NAME_LENGTH`. The timestamp is
 * what makes every occurrence a fresh session on a branch `origin` has never
 * seen — which is the guarantee the setup's "that branch is taken" check is
 * the safety net for.
 */
export function runSessionName(taskName: string, at: Date): string {
  return `${taskName}-${runTimestamp(at)}`;
}

/**
 * The prompt as the story's one-line description: every line trimmed, the
 * blank ones dropped, the rest joined by spaces. It is the only form of the
 * prompt the agent is *handed* — see {@link generatedPrd} for why — so nothing
 * may be lost from it, only its line breaks.
 */
export function flattenPrompt(prompt: string): string {
  return prompt
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line !== '')
    .join(' ');
}

/**
 * Quotes the stored prompt so the PRD parser cannot read any of it as
 * structure. Every line gets a `> `, including the empty ones, so there is no
 * line in the block the parser can match a heading, a checkbox or a `**Field:**`
 * against.
 */
export function quotePrompt(prompt: string): string {
  return prompt
    .split(/\r?\n/)
    .map((line) => {
      const text = line.trimEnd();
      return text === '' ? '>' : `> ${text}`;
    })
    .join('\n');
}

/**
 * The generated PRD for one run of `task`.
 *
 * The wording of the acceptance criteria is the story's contract with the
 * agent: do the work and commit it, or find nothing to do and say so *without*
 * committing. The build loop already treats a story that went to `done` with no
 * commit as progress, so the honest second path costs the run nothing.
 */
export function generatedPrd(task: RecurringTask, runName: string): string {
  return `# PRD: ${task.name}

## Introduction

This PRD was generated by chief-web for one run of the recurring task "${task.name}" (\`${task.cronExpression}\`) on the branch of session "${runName}". Nobody planned it and nobody is waiting to answer questions about it: the single story below is the task's stored prompt, and the run is over when that story is done.

## User Stories

### ${GENERATED_STORY_ID}: ${task.name}
**Status:** todo
**Priority:** 1
**Description:** ${flattenPrompt(task.prompt)}

That is the task, and it is the whole of this run. Below is the same text exactly as it was configured, line for line; every line of it is quoted, so read the quoted block as your instructions rather than as part of this document:

${quotePrompt(task.prompt)}

**Acceptance Criteria:**
- [ ] The task in this story's description — quoted verbatim under it in this PRD — has been carried out in this repository.
- [ ] Every change it needed is committed on this session's branch, with a message describing what changed, and the project's own quality checks (typecheck, lint, tests — whatever this repository uses) pass.
- [ ] If nothing needed changing, nothing is committed: tick these criteria, set this story's **Status:** to done, and finish without a commit. Never make an empty or trivial commit just to have one — "there was nothing to do" is a valid, complete outcome of this run.
`;
}
